const outcomes=[['🪐','Starfield VR cockpit → living starship','Stereo, head tracking, HUD and ship interaction can grow toward embodiment, hands, crew behaviour and spatial systems.','Mutar/OpenXR + Skyrim parity + Starfield authoring'],['🫴','Embodied hands and physical weapons','A transport-neutral pose contract separates Quest/OpenXR tracking from title-specific skeleton and IK work.','Universal Hands + Cyberpunk + Skyrim parity'],['🎬','Comfortable dialogue and cinematics','Immersive conversation, focused framing and room-fixed 3D theatre can be selected according to camera ownership.','Halo theatre + adaptive presentation'],['🧬','Convert resistant flat games','Escalate through framework, title adapter, reconstructed stereo, spatial screen or lawful independent recreation.','Route planner + UEVR/vorpX + reconstruction'],['🛸','Stephanos Spatial Bridge','A seated Quest 3 command bridge over the same canonical Stephanos brain with mission state preserved outside the headset.','Single-brain doctrine + Battle Bridge'],['🧰','Reusable VR conversion factory','Every experiment should leave adapters, tests, provenance and acceptance evidence so later titles start further ahead.','Capability Graph + Method Library']];
const fallbackSources=[['Halo MCC VR','rendering','Open-source reference','Multi-title runtime patterns and room-fixed 3D cutscene theatre.','cutscene theatre'],['OpenXR SDK Source','runtime','Authoritative implementation','Loader, API-layer and sample implementation behaviour.','runtime plumbing'],['Skyrim VR ecosystem','interaction','Native parity benchmark','Body, holsters, grabbing and character response decomposed into capabilities.','embodiment parity'],['Meta Quest Link / Air Link','delivery','Primary Quest 3 transport','Wireless PCVR delivery with layered failure attribution.','Quest 3 delivery'],['Starfield + Creation Kit','tooling','Authoritative title evidence','Authoring and runtime attachment points for Starfield-specific systems.','integration seams'],['Paradise Decay / creator evidence','field','Field evidence','Headset-use evidence for usability, setup, comfort and performance questions.','acceptance clues']];
const fallbackMethods=[['Capability Route Planner','active','Choose native, framework, title-adapter, reconstructed-stereo, spatial-screen or recreation routes from evidence.'],['Skyrim VR Parity Decomposition','active','Translate body, holsters, interaction and character response into reusable attachment points and tests.'],['Room-fixed 3D Cutscene Theatre','reference-proven','Preserve authored cinematic framing on a room-fixed stereo screen while retaining 6DoF head tracking.'],['Transport-neutral Hand Pose Contract','active','Separate tracking producers from title-specific skeleton adapters using a bounded pose contract and calibration.'],['Starfield Mutar OpenXR Baseline','proof-pending','Bind exact Starfield/provider identity to Meta OpenXR and Quest 3 Air Link proof.'],['Adaptive Dialogue Presentation','design-active','Choose immersive dialogue, focused conversation or theatre based on camera ownership and intent.']];
const concepts=[
{payload:'./concepts/spatial-bridge.b64.txt',title:'Spatial Bridge mission control',description:'A seated first-person command deck where hand-driven spatial controls, mission telemetry and an AI copilot share one persistent Stephanos workspace.',tags:['spatial','bridge','openxr','quest','hand','mission','workspace','telemetry','copilot']},
{payload:'./concepts/embodied-exploration.b64.txt',title:'Embodied exploration with an AI expedition guide',description:'Hand presence, environmental scanning, route planning and context-aware companion behaviour inside a fully spatial world.',tags:['hand','embodiment','interaction','companion','dialogue','quest','openxr','world','route']},
{payload:'./concepts/immersive-engineering.b64.txt',title:'Build, test and iterate at life size',description:'Manipulate a full-scale assembly with tracked hands while simulation, authoring and engineering data remain visible in three-dimensional context.',tags:['hand','interaction','tool','simulation','spatial','physics','authoring','openxr','build']},
{payload:'./concepts/spatial-collaboration.b64.txt',title:'Collaborative spatial mission room',description:'Remote participants, AI assistance, live task state and a shared 3D strategy surface projected into one persistent operational space.',tags:['spatial','workspace','mission','ai','dialogue','collaboration','world','bridge','task']}
];
let sources=[...fallbackSources],methods=[...fallbackMethods],workspace=null,active='all';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const sourceCount=$('#sourceCount'),techniqueCount=$('#techniqueCount'),targetCount=$('#targetCount'),researchTitle=$('#researchTitle'),badge=$('#badge'),liveMeta=$('#liveMeta'),search=$('#search'),refresh=$('#refresh');
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const norm=v=>String(v||'').toLowerCase().replace(/[^a-z0-9]+/g,' ');
$('#outcomes').innerHTML=outcomes.map(o=>`<article class="card"><div class="icon">${o[0]}</div><h3>${esc(o[1])}</h3><p>${esc(o[2])}</p><div class="unlock"><b>UNLOCKED BY</b><br>${esc(o[3])}</div></article>`).join('');
function switchView(view){$$('.viewpage').forEach(p=>p.classList.toggle('active',p.id===`view-${view}`));$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));if(view==='concepts')renderConcepts();window.scrollTo({top:$('.viewbar').offsetTop-62,behavior:'smooth'})}
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));
function renderSources(){const q=search.value.toLowerCase().trim();const rows=sources.filter(s=>(active==='all'||s[1]===active)&&(!q||s.join(' ').toLowerCase().includes(q)));$('#sources').innerHTML=rows.map(s=>`<article class="card source"><div class="type">${esc(s[2])}</div><h3>${esc(s[0])}</h3><p>${esc(s[3])}</p><div class="small">↳ ${esc(s[4])}</div></article>`).join('')}
function renderMethods(){$('#methodsGrid').innerHTML=methods.map(m=>`<article class="card method"><span class="status ${esc(m[1])}">${esc(m[1])}</span><div><h3>${esc(m[0])}</h3><p>${esc(m[2])}</p></div></article>`).join('')}
function techniqueWeight(status){const s=String(status||'').toLowerCase();if(s==='active'||s==='reference-proven')return 3;if(s==='proof-pending'||s==='design-active')return 2;return 1}
function researchItems(){const targets=Array.isArray(workspace?.targets)?workspace.targets.map(t=>({name:t.name||t.title||t.id||'Mission target',text:JSON.stringify(t),weight:2})):[];const techniqueItems=methods.map(m=>({name:m[0],text:m.join(' '),weight:techniqueWeight(m[1])}));return [...techniqueItems,...targets]}
function scoreConcept(c){let score=0;const hits=[];for(const item of researchItems()){const tokens=new Set(norm(item.text).split(' ').filter(Boolean));const matched=c.tags.filter(tag=>tokens.has(norm(tag).trim()));if(matched.length){score+=Math.min(4,matched.length)*item.weight;hits.push(item.name)}}return {score,hits:[...new Set(hits)].slice(0,4)}}
function conceptMedia(c,i){if(c.src)return `<img src="${c.src}" alt="Concept projection: ${esc(c.title)}" loading="${i?'lazy':'eager'}">`;if(c.imageError)return '<div style="padding:42px;color:#8da9c0">Concept view unavailable</div>';return '<div style="padding:42px;color:#8da9c0">Loading concept view…</div>'}
function renderConcepts(){const ranked=concepts.map(c=>({...c,...scoreConcept(c)})).sort((a,b)=>b.score-a.score||a.title.localeCompare(b.title));const max=Math.max(1,...ranked.map(c=>c.score));$('#conceptMeta').textContent=`Ranked against ${methods.length} current techniques${Array.isArray(workspace?.targets)?` and ${workspace.targets.length} mission targets`:''}. Recalculated with every 60-second research refresh.`;$('#conceptGallery').innerHTML=ranked.map((c,i)=>{const pct=Math.round(c.score/max*100);const match=c.hits.length?c.hits.map(esc).join(' · '):'No strong canonical technique match yet';return `<article class="card concept-card ${c.score?'':'dim'}"><div class="concept-media">${conceptMedia(c,i)}<div class="concept-overlay"><span class="concept-pill">Concept · not runtime proof</span><span class="concept-score">Research fit ${pct}%</span></div></div><div class="concept-copy"><h3>${i===0?'✦ ':''}${esc(c.title)}</h3><p>${esc(c.description)}</p><div class="concept-tags">${c.tags.slice(0,6).map(t=>`<span class="concept-tag">${esc(t)}</span>`).join('')}</div><div class="concept-match"><b>${c.score?'CURRENT SUPPORT':'FUTURE DIRECTION'}</b><br>${match}</div></div></article>`}).join('')}
async function loadConceptImages(){await Promise.all(concepts.map(async c=>{if(c.src||c.imageError)return;try{const r=await fetch(c.payload,{cache:'force-cache'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const b64=(await r.text()).replace(/\s+/g,'');if(!b64)throw new Error('empty payload');c.src=`data:image/jpeg;base64,${b64}`}catch{c.imageError=true}}));renderConcepts()}
function renderSnapshot(){workspace=null;sources=[...fallbackSources];methods=[...fallbackMethods];sourceCount.textContent=sources.length;techniqueCount.textContent=methods.length;targetCount.textContent='snapshot';researchTitle.textContent='Embedded VR research snapshot';renderSources();renderMethods();renderConcepts()}
function setState(mode,text){badge.className='badge '+mode;badge.innerHTML=`<span class="dot"></span>${mode==='live'?'LIVE · canonical research':mode==='pending'?'CONNECTING · verifying':'SNAPSHOT · live unavailable'}`;liveMeta.textContent=text||''}
const paths={workspace:['../../VR-Research-Lab/lab-workspace.json','https://raw.githubusercontent.com/Cheekyfellastef/stephan-os/main/VR-Research-Lab/lab-workspace.json'],registry:['../../VR-Research-Lab/knowledge-sources.json','https://raw.githubusercontent.com/Cheekyfellastef/stephan-os/main/VR-Research-Lab/knowledge-sources.json']};
async function firstJson(urls){let last;for(const url of urls){try{const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);return {data:await r.json(),url}}catch(e){last=e}}throw last||new Error('unavailable')}
function category(x){const t=norm(`${x.source_id} ${x.title}`);if(/hand|skyrim|vrik|higgs|planck/.test(t))return'interaction';if(/virtual desktop|air link|quest link|meta quest/.test(t))return'delivery';if(/creator|voodoo|paradise|beardo|headset/.test(t))return'field';if(/installer|creation kit|rai pal|deluxe/.test(t))return'tooling';if(/openxr sdk|openxr spec|reframework/.test(t))return'runtime';return'rendering'}
function sourceRow(x){return [x.title||x.source_id,category(x),String(x.status||x.priority||'registered').replaceAll('-',' '),String(x.promotion_rule||'Canonical evidence retained with provenance and reuse boundaries.').slice(0,190),[`licence: ${x.licence||'tracked'}`,x.snapshot_version||x.snapshot_release||x.snapshot_date||x.snapshot_commit?.slice(0,8)].filter(Boolean).join(' · ')]}
async function hydrate(){setState('pending','Refreshing canonical VR research…');try{const [w,r]=await Promise.all([firstJson(paths.workspace),firstJson(paths.registry)]);if(!Array.isArray(r.data.sources)||!r.data.sources.length)throw new Error('empty source registry');if(!Array.isArray(w.data.techniques)||!w.data.techniques.length)throw new Error('empty technique set');workspace=w.data;sources=r.data.sources.map(sourceRow);methods=w.data.techniques.map(x=>[x.name,x.status||'active',x.goal||'Reusable VR method']);sourceCount.textContent=sources.length;techniqueCount.textContent=methods.length;targetCount.textContent=Array.isArray(w.data.targets)?w.data.targets.length:'—';researchTitle.textContent=`The ${sources.length}-source live VR stack`;renderSources();renderMethods();renderConcepts();const local=w.url.startsWith('..')&&r.url.startsWith('..');const stamp=w.data.updatedAt?new Date(w.data.updatedAt).toLocaleString():'current';setState('live',`${local?'Battle Bridge / repo-local':'GitHub main'} · workspace ${stamp} · concepts reranked · auto-refresh 60s`)}catch(e){renderSnapshot();setState('snapshot',`Embedded snapshot in use · ${e.message||'live fetch failed'}`)}}
search.addEventListener('input',renderSources);$$('.filter').forEach(b=>b.addEventListener('click',()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');active=b.dataset.filter;renderSources()}));refresh.addEventListener('click',hydrate);renderSnapshot();loadConceptImages();hydrate();setInterval(hydrate,60000);
