export const AUTONOMY_BUILD_TRACK_SCHEMA = 'stephanos.autonomy-build-track.v1';
export const AUTONOMY_BUILD_TRACK_STATUS_ID = 'autonomy-build-track-current';

export const AUTONOMY_BUILD_TRACK_STATES = Object.freeze({
  PASS: 'PASS',
  BLOCKED: 'BLOCKED',
  WAITING: 'WAITING',
  NOT_REACHED: 'NOT_REACHED',
  UNKNOWN: 'UNKNOWN',
});

export const AUTONOMY_BUILD_TRACK_GATES = Object.freeze([
  'SYNC','CONTROL_PLANE','HEARTBEAT','ELIGIBLE_GOAL','SELECT','CLAIM','SOURCE_CHANGED','TESTED','TERMINAL_RECEIPT','REVIEW_HANDOFF','RELEASE','SELECT_NEXT',
]);
function text(value, fallback = '') { const normalized = String(value ?? '').trim(); return normalized || fallback; }
function freezeGate(id, state, reason = '') { return Object.freeze({ id, state, reason: text(reason) }); }
function issueFromMission(mission = {}) { const direct=Number(mission.issueNumber||mission.issue||0); if(Number.isSafeInteger(direct)&&direct>0)return direct; const parsed=Number(text(mission.missionId).match(/^critical-([1-9]\d*)-elastic-goal/i)?.[1]||0); return Number.isSafeInteger(parsed)&&parsed>0?parsed:null; }
function selectedMission(conveyor={}) { return conveyor?.elasticAdmission?.selectedMission||conveyor?.projection?.activeMission||conveyor?.missionRecord||null; }
function dispatchFacts(conveyor={}) { const elastic=conveyor?.elasticIgnition||{}, active=conveyor?.activeMissionIgnition||{}; const dispatched=Number(elastic.dispatchCount||0)>0||active.published===true||active.classification==='CRITICAL_ACTIVE_MISSION_ALREADY_RUNNING'; const blocked=elastic.ok===false||active.ok===false; const reason=(Array.isArray(elastic.held)&&elastic.held.length?elastic.held.map(i=>text(i?.reason)).filter(Boolean).join(','):'')||(Array.isArray(active.blockers)?active.blockers.map(text).filter(Boolean).join(','):'')||text(elastic.classification||active.classification); return Object.freeze({dispatched,blocked,reason}); }
function firstActionableGate(gates=[]) { return gates.find(g=>g.state===AUTONOMY_BUILD_TRACK_STATES.BLOCKED)||gates.find(g=>g.state===AUTONOMY_BUILD_TRACK_STATES.WAITING)||gates.find(g=>g.state===AUTONOMY_BUILD_TRACK_STATES.NOT_REACHED)||gates.find(g=>g.state===AUTONOMY_BUILD_TRACK_STATES.UNKNOWN)||null; }
function buildTrack({timestampUtc,sourceHead='',missionId='',issueNumber=null,actionId='',gates=[]}={}) { const actionable=firstActionableGate(gates); return Object.freeze({schemaVersion:AUTONOMY_BUILD_TRACK_SCHEMA,timestampUtc:text(timestampUtc),sourceHead:text(sourceHead).toLowerCase(),missionId:text(missionId),issueNumber:Number.isSafeInteger(issueNumber)&&issueNumber>0?issueNumber:null,actionId:text(actionId),gates:Object.freeze(gates),currentGate:actionable?.id||'COMPLETE',currentState:actionable?.state||AUTONOMY_BUILD_TRACK_STATES.PASS,blocker:actionable?.state===AUTONOMY_BUILD_TRACK_STATES.BLOCKED?actionable.reason:'',autonomousLoopProven:gates.length>0&&gates.every(g=>g.state===AUTONOMY_BUILD_TRACK_STATES.PASS)}); }
export function projectHeartbeatAutonomyBuildTrack({conveyorResult=null,sourceBuild=null,timestampUtc=new Date().toISOString()}={}) { const conveyorOk=conveyorResult?.ok===true, mission=selectedMission(conveyorResult||{}), missionId=text(mission?.missionId||conveyorResult?.missionRecord?.missionId), issueNumber=issueFromMission(mission||conveyorResult?.missionRecord||{}); const selected=Boolean(missionId||text(conveyorResult?.projection?.selectedItem?.itemId)||conveyorResult?.classification==='ELASTIC_GOAL_MISSION_SELECTED'||conveyorResult?.classification==='WAIT_ACTIVE_MISSION'); const dispatch=dispatchFacts(conveyorResult||{}), processed=sourceBuild?.processed===true, success=processed&&sourceBuild?.success===true, buildBlocked=processed&&sourceBuild?.success===false, claimPass=processed||dispatch.dispatched; const sourceHead=text(conveyorResult?.elasticIgnition?.sourceRevision||conveyorResult?.activeMissionIgnition?.sourceRevision||sourceBuild?.sourceHead), actionId=text(sourceBuild?.actionId), conveyorBlocker=text(conveyorResult?.blocker||conveyorResult?.classification||conveyorResult?.finalVerdict), buildReason=text(sourceBuild?.error||sourceBuild?.reason||sourceBuild?.finalVerdict); const gates=[freezeGate('HEARTBEAT',conveyorOk?'PASS':'BLOCKED',conveyorOk?'':conveyorBlocker),freezeGate('ELIGIBLE_GOAL',selected?'PASS':(conveyorOk?'WAITING':'NOT_REACHED'),selected?'':'NO_ELIGIBLE_GOAL_SELECTED'),freezeGate('SELECT',selected?'PASS':'NOT_REACHED'),freezeGate('CLAIM',claimPass?'PASS':selected&&dispatch.blocked?'BLOCKED':selected?'WAITING':'NOT_REACHED',claimPass?'':dispatch.reason||buildReason||'CLAIM_NOT_YET_OBSERVED'),freezeGate('SOURCE_CHANGED',success?'PASS':buildBlocked?'BLOCKED':'NOT_REACHED',buildBlocked?buildReason:''),freezeGate('TESTED',success?'PASS':'NOT_REACHED'),freezeGate('TERMINAL_RECEIPT',success?'PASS':'NOT_REACHED'),freezeGate('REVIEW_HANDOFF','NOT_REACHED'),freezeGate('RELEASE','NOT_REACHED'),freezeGate('SELECT_NEXT','NOT_REACHED')]; return buildTrack({timestampUtc,sourceHead,missionId,issueNumber,actionId,gates}); }
function recordMs(record) { if (!record || typeof record !== 'object') return 0; const parsed=Date.parse(text(record.timestampUtc||record.checkedAtUtc||record.createdAt)); return Number.isFinite(parsed)?parsed:0; }
function latestStatus(records=[],statusId) { return (Array.isArray(records)?records:[]).filter(r=>text(r?.statusId)===statusId).sort((l,r)=>recordMs(r)-recordMs(l))[0]||null; }
function isFresh(record,nowMs,staleAfterMs) { const ms=recordMs(record); return Boolean(ms&&nowMs-ms<=staleAfterMs); }
function syncGate(sync,fresh) { if(!sync)return freezeGate('SYNC','UNKNOWN','SYNC_STATUS_MISSING'); const value=text(sync.status||sync.classification||sync.evaluation?.classification).toUpperCase(); if(!fresh)return freezeGate('SYNC','UNKNOWN','SYNC_STATUS_STALE'); if(value.includes('BLOCK'))return freezeGate('SYNC','BLOCKED',value); if(value.includes('SYNC_NO_CHANGE')||value.includes('SYNC')||value.includes('PASS'))return freezeGate('SYNC','PASS'); return freezeGate('SYNC','UNKNOWN',value||'SYNC_STATUS_UNKNOWN'); }
function controlPlaneGate({refresh,refreshFresh,heartbeat,heartbeatFresh}) { if(heartbeatFresh&&heartbeat?.autonomyTrack?.gates?.some(g=>g?.id==='HEARTBEAT'&&g?.state==='PASS'))return freezeGate('CONTROL_PLANE','PASS'); const blocker=text(refresh?.blocker); if(blocker.startsWith('CONTROL_PLANE_'))return freezeGate('CONTROL_PLANE','BLOCKED',blocker); if(!refresh)return freezeGate('CONTROL_PLANE','UNKNOWN','CONTROL_PLANE_STATUS_MISSING'); if(!refreshFresh)return freezeGate('CONTROL_PLANE','UNKNOWN',blocker||'CONTROL_PLANE_STATUS_STALE'); const status=text(refresh.status||refresh.classification).toUpperCase(); if(status.includes('BLOCK')&&blocker)return freezeGate('CONTROL_PLANE','BLOCKED',blocker); if(!blocker&&(status.includes('COMPLETE')||status.includes('PASS')||refresh.exactHeadProofOk===true))return freezeGate('CONTROL_PLANE','PASS'); return freezeGate('CONTROL_PLANE','UNKNOWN',blocker||status||'CONTROL_PLANE_STATUS_UNKNOWN'); }
export function projectWorkspaceAutonomyBuildTrack({statusRecords=[],nowMs=Date.now(),staleAfterMs=60*60*1000}={}) { const sync=latestStatus(statusRecords,'battle-bridge-github-sync-current'), refresh=latestStatus(statusRecords,'post-sync-runtime-refresh-current'), heartbeat=latestStatus(statusRecords,AUTONOMY_BUILD_TRACK_STATUS_ID), syncFresh=isFresh(sync,nowMs,staleAfterMs), refreshFresh=isFresh(refresh,nowMs,staleAfterMs), heartbeatFresh=isFresh(heartbeat,nowMs,staleAfterMs), heartbeatTrack=heartbeatFresh&&heartbeat?.autonomyTrack?.schemaVersion===AUTONOMY_BUILD_TRACK_SCHEMA?heartbeat.autonomyTrack:null; const gates=[syncGate(sync,syncFresh),controlPlaneGate({refresh,refreshFresh,heartbeat,heartbeatFresh}),...(heartbeatTrack?.gates||['HEARTBEAT','ELIGIBLE_GOAL','SELECT','CLAIM','SOURCE_CHANGED','TESTED','TERMINAL_RECEIPT','REVIEW_HANDOFF','RELEASE','SELECT_NEXT'].map(id=>freezeGate(id,'NOT_REACHED')))]; return buildTrack({timestampUtc:new Date(nowMs).toISOString(),sourceHead:heartbeatTrack?.sourceHead||text(sync?.sourceHead||sync?.localHeadAfter||sync?.remoteHeadObserved),missionId:heartbeatTrack?.missionId||'',issueNumber:heartbeatTrack?.issueNumber||null,actionId:heartbeatTrack?.actionId||'',gates}); }
