import test from 'node:test';
import assert from 'node:assert/strict';
import { runGuardedContinuousRepairCycle } from './guardedGoalRunnerContinuousRepairV1.mjs';
import { createExecutionReceipt } from './executionReceiptV1.mjs';

const HEAD='a'.repeat(40); const BASE='b'.repeat(40);
const finding={id:'P1-loop',severity:'P1',bounded:true,file:'shared/agents/example.mjs',message:'repair me'};
function snapshot(overrides={}){return {repository:'cheekyfellastef/stephan-os',issueNumber:1497,prNumber:1617,branch:'feat/example',baseSha:BASE,expectedBaseSha:BASE,headSha:HEAD,activeLaneKnown:true,currentPrCount:1,reviewProofAvailable:true,reviewHeadSha:HEAD,findingsEvidenceAvailable:true,findings:[finding],activeRepairOrders:[],receipts:[],nowUtc:'2026-07-29T15:00:00.000Z',workerAvailability:{githubFirstAvailable:true,githubFirstWorkerId:'github-worker'},receiptTimestampUtc:'2026-07-29T15:00:00.000Z',receiptHeartbeatExpiresAtUtc:'2026-07-29T15:02:00.000Z',...overrides};}
function harness(states,extra={}){let i=0;const calls={cycle:[],execution:[],dispatch:[],verify:[]};return {calls,options:{loadSnapshot:async()=>states[Math.min(i++,states.length-1)],persistCycleReceipt:async r=>calls.cycle.push(r),persistExecutionReceipt:async r=>calls.execution.push(r),dispatchRepair:async o=>{calls.dispatch.push(o);return {accepted:true,workerTaskId:'worker-1'};},requestExactHeadVerification:async r=>{calls.verify.push(r);return {accepted:true,verificationId:'verify-1'};},maxIterations:states.length,...extra}};}
function receipt(order,state,sequence,predecessorReceiptId=''){return createExecutionReceipt({repository:order.repository,issueNumber:order.issueNumber,prNumber:order.prNumber,branch:order.branch,sourceHead:order.headSha,workerId:order.assignedWorkerId,workerType:order.worker.workerType,executionId:order.executionId,leaseKey:order.leaseKey,state,phase:state,sequence,predecessorReceiptId,timestampUtc:new Date(Date.parse('2026-07-29T15:00:00.000Z')+(sequence-1)*1000).toISOString(),heartbeatExpiresAtUtc:'2026-07-29T15:02:00.000Z',proofRefs:['proof'],expectedNextAction:state==='completed'?'':'continue'});}
function completedChain(order){const queued=receipt(order,'queued',1);const accepted=receipt(order,'accepted',2,queued.receiptId);const started=receipt(order,'started',3,accepted.receiptId);return [queued,accepted,started,receipt(order,'completed',4,started.receiptId)];}

test('automatically dispatches a bounded review repair',async()=>{const h=harness([snapshot()]);const result=await runGuardedContinuousRepairCycle(h.options);assert.equal(h.calls.dispatch.length,1);assert.equal(h.calls.execution.length,1);assert.equal(h.calls.cycle[0].status,'repair-dispatched');assert.equal(result.status,'BLOCKED_ITERATION_BUDGET');});

test('requests exact-head verification after repair completion',async()=>{const order={repository:'cheekyfellastef/stephan-os',issueNumber:1497,prNumber:1617,branch:'feat/example',headSha:HEAD,executionId:'exec',leaseKey:'lease',assignedWorkerId:'github-worker',worker:{workerType:'github-first'},laneGeneration:1};const h=harness([snapshot({findings:[],activeRepairOrders:[order],receipts:completedChain(order),ciGreen:false,ciHeadSha:HEAD,mergeable:true})]);const result=await runGuardedContinuousRepairCycle(h.options);assert.equal(h.calls.verify.length,1);assert.equal(result.status,'BLOCKED_ITERATION_BUDGET');});

test('stops at merge-ready and never gains merge authority',async()=>{const order={repository:'cheekyfellastef/stephan-os',issueNumber:1497,prNumber:1617,branch:'feat/example',headSha:HEAD,executionId:'exec',leaseKey:'lease',assignedWorkerId:'github-worker',worker:{workerType:'github-first'},laneGeneration:1};const h=harness([snapshot({findings:[],activeRepairOrders:[order],receipts:completedChain(order),ciGreen:true,ciHeadSha:HEAD,mergeable:true})]);const result=await runGuardedContinuousRepairCycle(h.options);assert.equal(result.status,'MERGE_READY');assert.equal(result.mergeAuthority,false);assert.equal(result.approvalAuthority,false);});

test('enforces a bounded repair budget',async()=>{const h=harness([snapshot()],{history:[{status:'repair-dispatched',headSha:HEAD}],maxRepairsPerHead:1});const result=await runGuardedContinuousRepairCycle(h.options);assert.equal(result.status,'BLOCKED_REPAIR_BUDGET');assert.equal(h.calls.dispatch.length,0);});
