import test from 'node:test';
import assert from 'node:assert/strict';
import { createExecutionReceipt, EXECUTION_RECEIPT_SCHEMA_VERSION } from './executionReceiptV1.mjs';
import { buildGuardedRepairDeduplicationKey, evaluateGuardedRepairLoop, routeGuardedRepairWorker } from './guardedGoalRunnerRepairLoopV1.mjs';

const BASE = 'a'.repeat(40); const HEAD = 'b'.repeat(40); const BRANCH = 'fix/goal-dashboard-truth'; const NOW = '2026-07-25T12:00:00.000Z';
const FINDINGS = [
  { id: 'P2-source-label', severity: 'P2', type: 'review_finding', bounded: true, file: 'shared/runtime/goalDashboardStatusProjection.mjs' },
  { id: 'P2-receipt-binding', severity: 'P2', type: 'review_finding', bounded: true, file: 'shared/runtime/goalDashboardStatusProjection.test.mjs' },
];
function input(overrides = {}) { return { repository: 'cheekyfellastef/stephan-os', issueNumber: 1385, prNumber: 1582, branch: BRANCH, baseSha: BASE, expectedBaseSha: BASE, headSha: HEAD, reviewHeadSha: HEAD, reviewProofAvailable: true, activeLaneKnown: true, currentPrCount: 1, findingsEvidenceAvailable: true, findings: FINDINGS, nowUtc: NOW, receiptTimestampUtc: NOW, receiptHeartbeatExpiresAtUtc: '2026-07-25T12:02:00.000Z', proofRefs: ['proofs/pr-1582-review'], allowedTests: ['node --test shared/runtime/goalDashboardStatusProjection.test.mjs'], workerAvailability: { githubFirstAvailable: true }, ...overrides }; }
function admitted(overrides = {}) { return evaluateGuardedRepairLoop(input(overrides)); }
function receipt(order, state, overrides = {}) { return createExecutionReceipt({ repository: order.repository, issueNumber: order.issueNumber, prNumber: order.prNumber, branch: order.branch, sourceHead: order.headSha, workerId: order.assignedWorkerId, workerType: order.worker.workerType, executionId: order.executionId, leaseKey: order.leaseKey, state, phase: state, sequence: 1, timestampUtc: NOW, heartbeatExpiresAtUtc: '2026-07-25T12:02:00.000Z', blocker: state === 'stalled' ? 'WAITING_EXTERNAL_PROOF' : '', operatorActionRequired: false, proofRefs: ['proofs/pr-1582-review'], expectedNextAction: ['completed', 'failed', 'cancelled'].includes(state) ? '' : 'Continue bounded repair.', ...overrides }); }

test('deduplication is exact-head and unambiguously finding-set bound', () => { const first = buildGuardedRepairDeduplicationKey(input()); assert.equal(first, buildGuardedRepairDeduplicationKey(input({ findings: [...FINDINGS].reverse() }))); assert.notEqual(first, buildGuardedRepairDeduplicationKey(input({ headSha: 'c'.repeat(40) }))); assert.notEqual(buildGuardedRepairDeduplicationKey(input({ findings: [{ id: 'a,b', severity: 'P1', bounded: true }, { id: 'c', severity: 'P1', bounded: true }] })), buildGuardedRepairDeduplicationKey(input({ findings: [{ id: 'a', severity: 'P1', bounded: true }, { id: 'b,c', severity: 'P1', bounded: true }] }))); });
test('new repair has canonical queued receipt and finding-bound execution identity', () => { const result = admitted(); assert.equal(result.verdict, 'known-blocker-repair-admitted'); assert.equal(result.nextReceipt.schemaVersion, EXECUTION_RECEIPT_SCHEMA_VERSION); assert.equal(result.nextReceipt.state, 'queued'); assert.equal(result.nextReceipt.workerId, result.repairOrder.assignedWorkerId); assert.match(result.repairOrder.executionId, /-execution$/); });
test('canonical chain and assigned worker identity are required', () => { const first = admitted(); const active = admitted({ activeRepairOrders: [first.repairOrder], receipts: [receipt(first.repairOrder, 'started')] }); assert.equal(active.verdict, 'repair-already-active'); const wrongWorker = receipt(first.repairOrder, 'started', { workerId: 'worker-other' }); assert.equal(admitted({ activeRepairOrders: [first.repairOrder], receipts: [wrongWorker] }).verdict, 'abort-invalid-canonical-receipt-chain'); const broken = [receipt(first.repairOrder, 'started'), receipt(first.repairOrder, 'completed', { sequence: 9, predecessorReceiptId: 'unrelated', timestampUtc: '2026-07-25T12:01:00.000Z' })]; assert.equal(admitted({ activeRepairOrders: [first.repairOrder], receipts: broken }).verdict, 'abort-invalid-canonical-receipt-chain'); });
test('expired active heartbeat is stale rather than indefinitely active', () => { const first = admitted(); const result = admitted({ nowUtc: '2026-07-25T12:03:00.000Z', activeRepairOrders: [first.repairOrder], receipts: [receipt(first.repairOrder, 'started')] }); assert.equal(result.verdict, 'repair-stale'); assert.equal(result.nextAction, 'WAIT_FOR_STALE_WORKER_ABORT'); });
test('completed receipt cannot be borrowed from another lane', () => { const first = admitted(); const foreign = { ...first.repairOrder, repository: 'other/repo' }; const result = admitted({ findings: [], ciGreen: true, ciHeadSha: HEAD, mergeable: true, activeRepairOrders: [foreign], receipts: [receipt(foreign, 'completed')] }); assert.equal(result.verdict, 'abort-missing-canonical-receipt'); });
test('each proof category requires its own exact-head binding', () => { const first = admitted(); const complete = receipt(first.repairOrder, 'completed'); assert.equal(admitted({ findings: [], ciGreen: true, ciHeadSha: 'c'.repeat(40), mergeable: true, activeRepairOrders: [first.repairOrder], receipts: [complete] }).verdict, 'repair-published-awaiting-ci'); const ready = admitted({ findings: [], ciGreen: true, ciHeadSha: HEAD, mergeable: true, activeRepairOrders: [first.repairOrder], receipts: [complete] }); assert.equal(ready.verdict, 'safe-to-merge-with-expected-head'); const runtimeStale = admitted({ findings: [], merged: true, ciGreen: true, ciHeadSha: HEAD, operatorApprovalRecorded: true, approvalHeadSha: HEAD, approvalPrNumber: 1582, runtimeProofRequired: true, runtimeProofGreen: true, runtimeHeadSha: 'c'.repeat(40), activeRepairOrders: [first.repairOrder], receipts: [complete] }); assert.equal(runtimeStale.verdict, 'repair-published-awaiting-ci'); });
test('merged completion requires explicit exact-head operator approval', () => { const first = admitted(); const complete = receipt(first.repairOrder, 'completed'); const missing = admitted({ findings: [], merged: true, ciGreen: true, ciHeadSha: HEAD, runtimeProofRequired: false, activeRepairOrders: [first.repairOrder], receipts: [complete] }); assert.equal(missing.verdict, 'abort-missing-exact-head-approval'); const green = admitted({ findings: [], merged: true, ciGreen: true, ciHeadSha: HEAD, operatorApprovalRecorded: true, approvalHeadSha: HEAD, approvalPrNumber: 1582, runtimeProofRequired: false, activeRepairOrders: [first.repairOrder], receipts: [complete] }); assert.equal(green.verdict, 'goal-green'); });
test('terminal failure allocates a distinct retry execution and lease', () => { const first = admitted(); const retry = admitted({ activeRepairOrders: [first.repairOrder], receipts: [receipt(first.repairOrder, 'failed')] }); assert.equal(retry.verdict, 'known-blocker-repair-admitted'); assert.notEqual(retry.repairOrder.executionId, first.repairOrder.executionId); assert.notEqual(retry.repairOrder.leaseKey, first.repairOrder.leaseKey); assert.equal(retry.repairOrder.retryOrdinal, 2); assert.equal(retry.nextReceipt.sequence, 1); });
test('changed finding set gets distinct identity after terminal reconciliation', () => { const first = admitted(); const changed = [...FINDINGS, { id: 'P1-new', severity: 'P1', bounded: true }]; const next = admitted({ findings: changed, activeRepairOrders: [first.repairOrder], receipts: [receipt(first.repairOrder, 'cancelled')] }); assert.equal(next.verdict, 'known-blocker-repair-admitted'); assert.notEqual(next.repairOrder.executionId, first.repairOrder.executionId); });
test('same-head and prior-head active executions block concurrency', () => { const first = admitted(); const changed = [...FINDINGS, { id: 'P1-new', severity: 'P1', bounded: true }]; assert.equal(admitted({ findings: changed, activeRepairOrders: [first.repairOrder], receipts: [receipt(first.repairOrder, 'started')] }).verdict, 'abort-active-finding-set-change'); const nextHead = 'd'.repeat(40); assert.equal(admitted({ headSha: nextHead, reviewHeadSha: nextHead, activeRepairOrders: [first.repairOrder], receipts: [receipt(first.repairOrder, 'started')] }).verdict, 'abort-stale-worker-active'); });
test('safety and routing gates fail closed', () => { assert.equal(admitted({ reviewProofAvailable: false }).verdict, 'abort-missing-proof'); assert.equal(admitted({ reviewHeadSha: 'c'.repeat(40) }).verdict, 'abort-missing-proof'); assert.equal(admitted({ currentPrCount: 2 }).verdict, 'abort-conflicting-pr'); assert.equal(admitted({ expectedBaseSha: 'c'.repeat(40) }).verdict, 'abort-stale-base'); assert.equal(admitted({ findingsEvidenceAvailable: false }).verdict, 'abort-missing-proof'); assert.equal(routeGuardedRepairWorker({}).route, 'BLOCKED_UNSAFE_OR_UNKNOWN'); assert.equal(routeGuardedRepairWorker({ remoteCodexAvailable: true }).workerType, 'remote-codex'); });
