import test from 'node:test';import assert from 'node:assert/strict';import{PRIVACY_TILE_EVIDENCE_INPUT_SCHEMA_VERSION as IS,PRIVACY_TILE_EVIDENCE_RECORD_SCHEMA_VERSION as RS,PRIVACY_TILE_CANONICAL_STALE_AFTER_MS as ST,PRIVACY_TILE_MAX_RECORDS as MR,buildPrivacyTileEvidenceProjectionV1 as build,validatePrivacyEvidenceRecordV1 as validate}from'./privacyTileEvidenceProjectionV1.mjs';
const NOW=Date.parse('2026-08-14T20:00:00.000Z'),iso=n=>new Date(n).toISOString();
function rec(x={}){return{schemaVersion:RS,recordId:'r-1',domain:'AI_PROVIDER_TRANSPARENCY',classification:'CONFIRMED_INTERVENTION',sourceClass:'SYNTHETIC_TEST_FIXTURE',subjectRef:'provider-openai',summary:'Visible bounded provider notice.',observedAtUtc:iso(NOW-1000),freshnessBasisUtc:iso(NOW-1000),evidenceRefs:['evidence://fixture/r-1'],consentState:null,rightsRequestState:null,rightsOpenedAtUtc:null,rightsDeadlineUtc:null,networkContactKind:null,networkDestinationCategory:null,displayPrivacySetting:null,limitations:[],...x}}
const input=records=>({schemaVersion:IS,snapshotId:'privacy-snapshot-1',records}),run=records=>build(input(records),{evaluationNowMs:NOW});
test('separates truth buckets',()=>{const p=run([rec(),rec({recordId:'r-2',classification:'INFERRED_COLLECTION_RISK'}),rec({recordId:'r-3',classification:'PROVIDER_SAYS_NO_RECORD'}),rec({recordId:'r-4',classification:'STALE_EVIDENCE',freshnessBasisUtc:iso(NOW-ST-1)})]);assert.deepEqual(p.truthCounts,{total:4,confirmed:1,inferred:1,unknown:1,stale:1})});
test('absent device consent is unproven',()=>{const p=run([rec({domain:'DEVICE_DISPLAY_PRIVACY',displayPrivacySetting:'UNKNOWN'})]);assert.equal(p.consent.unprovenCount,1);assert.ok(p.unknowns.includes('DISPLAY_PRIVACY_SETTING_UNKNOWN'))});
test('network contact is contact only',()=>{const p=run([rec({domain:'NETWORK_CONTACT',classification:'INFERRED_LATENCY_OR_NETWORK_ANOMALY',sourceClass:'SANITIZED_NETWORK_METADATA',networkContactKind:'CONTACT_OBSERVED',networkDestinationCategory:'VENDOR_TELEMETRY'})]);assert.equal(p.records[0].contactOnly,true);assert.equal(validate(rec({domain:'NETWORK_CONTACT',classification:'CONFIRMED_COLLECTION',networkContactKind:'CONTACT_OBSERVED',networkDestinationCategory:'VENDOR'}),{evaluationNowMs:NOW}).valid,false)});
test('unknown display setting stays unknown',()=>assert.equal(run([rec({domain:'DEVICE_DISPLAY_PRIVACY',displayPrivacySetting:null})]).records[0].effectiveDisplayPrivacySetting,'UNKNOWN'));
test('provider no record is not no processing',()=>{const p=run([rec({classification:'PROVIDER_SAYS_NO_RECORD'})]);assert.equal(p.truthCounts.unknown,1);assert.ok(p.unknowns.includes('ABSENCE_OF_DISCLOSURE_IS_NOT_PROOF_OF_NO_PROCESSING'))});
test('stale visible and future invalid',()=>{assert.equal(run([rec({freshnessBasisUtc:iso(NOW-ST-1)})]).truthCounts.stale,1);assert.equal(validate(rec({observedAtUtc:iso(NOW+300001),freshnessBasisUtc:iso(NOW)}),{evaluationNowMs:NOW}).valid,false)});
test('caller cannot widen freshness',()=>assert.equal(build(input([rec()]),{evaluationNowMs:NOW,staleAfterMs:9e15}).valid,false));
test('duplicate ids invalid',()=>assert.equal(run([rec(),rec()]).valid,false));
test('collection bounds',()=>{assert.equal(build({...input([]),records:{}},{evaluationNowMs:NOW}).valid,false);assert.equal(run(Array.from({length:MR+1},(_,i)=>rec({recordId:`r-${i}`}))).valid,false)});
test('unsupported enums invalid',()=>{assert.equal(validate(rec({classification:'NO_SCAN'}),{evaluationNowMs:NOW}).valid,false);assert.equal(validate(rec({domain:'BROWSER_HISTORY'}),{evaluationNowMs:NOW}).valid,false);assert.equal(validate(rec({domain:'DATA_RIGHTS',rightsRequestState:'MAGIC'}),{evaluationNowMs:NOW}).valid,false)});
test('sensitive and unsafe evidence rejected',()=>{for(const x of[{summary:'raw export contains secret'},{subjectRef:'account-id'},{evidenceRefs:['evidence://../secret']},{evidenceRefs:['evidence://C:/Users/Stephan/a']},{evidenceRefs:['evidence://fixture/123456789']}])assert.equal(validate(rec(x),{evaluationNowMs:NOW}).valid,false)});
test('rights deadline is read only',()=>{const p=run([rec({domain:'DATA_RIGHTS',classification:'REQUESTED_BUT_WITHHELD',sourceClass:'RIGHTS_REQUEST_RECEIPT',rightsRequestState:'RESPONSE_DUE',rightsOpenedAtUtc:iso(NOW-100000),rightsDeadlineUtc:iso(NOW-1)})]);assert.equal(p.rights.overdueCount,1);assert.equal(p.recommendedNextReviewAction.actionClass,'REVIEW_OVERDUE_RIGHTS_REQUEST');assert.equal(p.authority.legalSubmissionAllowed,false);assert.equal(p.authority.deletionAllowed,false)});
test('empty evidence is unknown',()=>assert.equal(run([]).posture,'UNKNOWN'));
test('all authority flags false',()=>assert.ok(Object.values(run([rec()]).authority).every(v=>v===false)));
test('deterministic provider neutral output',()=>{const a=run([rec({recordId:'b'}),rec({recordId:'a',classification:'INFERRED_COLLECTION_RISK'})]),b=run([rec({recordId:'a',classification:'INFERRED_COLLECTION_RISK'}),rec({recordId:'b'})]);assert.equal(a.projectionId,b.projectionId);assert.deepEqual(a.records.map(r=>r.recordId),['a','b'])});
