export const SOVEREIGN_COMMANDER_LEARNING_INTAKE_SCHEMA_V1 = 'stephanos.sovereign-commander-learning-intake.v1';

export const SOVEREIGN_COMMANDER_LEARNING_FAILURE_CLASSES_V1 = Object.freeze([
  'PATH_UNKNOWN',
  'CAPABILITY_MISSING',
  'CANNOT_DISCOVER_SURFACE',
  'NO_VERIFICATION_METHOD',
  'UNSUPPORTED_OPERATION',
]);
