import test from 'node:test';
import assert from 'node:assert/strict';
import { buildUiAgentCanonicalExperienceContractV1 as build } from './uiAgentCanonicalExperienceContractV1.mjs';
import { UI_AGENT_EXPERIENCE_INVENTORY_SCHEMA_VERSION } from './uiAgentExperienceInventoryV1.mjs';

const ids=['stephanos-landing-page','ai-console','goal-dashboard','music-tile','vr-research-lab','vr-link','sovereignty','wealth','privacy','trading-laboratory','autonomous-build-controls','command-deck','ignition-splash','desktop-browser','windows-edge','ipad','iphone','whatsapp','voice','quest3-spatial'];
function inventory(overrides={}){ return { schemaVersion:UI_AGENT_EXPERIENCE_INVENTORY_SCHEMA_VERSION, inventoryId:'ui-inventory-test', valid:true, nextMilestone:'M3_PUBLISH_CANONICAL_EXPERIENCE_CONTRACT_AND_DESIGN_MAP', surfaces:ids.map((surfaceId)=>({surfaceId})), coverage:{canonicalTargetCount:ids.length,coveredCanonicalCount:ids.length,coveredCanonical:[...ids],missingCanonical:[]}, ...overrides }; }

test('publishes one deterministic cross-surface design map from an M3-ready inventory',()=>{ const a=build({inventory:inventory()}); const b=build({inventory:inventory()}); assert.equal(a.valid,true); assert.equal(a.state,'CANONICAL_DESIGN_MAP_READY_FOR_IMPLEMENTATION_PLANNING'); assert.equal(a.contractId,b.contractId); assert.equal(a.surfaces.length,20); assert.ok(a.surfaces.every((s)=>s.experienceLanguage==='STEPHANOS_DELUXE_V1')); });
test('proof plan is explicit and initially unsatisfied',()=>{ const out=build({inventory:inventory()}); assert.ok(out.proofPlan.length>=10); assert.ok(out.proofPlan.every((p)=>p.required===true&&p.satisfied===false&&p.evidenceRef===null)); });
test('all mutation and product authority remains false',()=>{ const out=build({inventory:inventory()}); assert.ok(Object.values(out.authority).every((v)=>v===false)); });
test('incomplete canonical coverage fails closed',()=>{ const inv=inventory(); inv.surfaces=inv.surfaces.slice(1); assert.equal(build({inventory:inv}).valid,false); });
test('inventory must explicitly be M3 ready',()=>{ assert.equal(build({inventory:inventory({nextMilestone:'M2_COMPLETE_SOURCE_AND_PRESENTATION_SURFACE_DISCOVERY'})}).valid,false); });
test('duplicate surface identities fail closed',()=>{ const inv=inventory(); inv.surfaces=[...inv.surfaces,{surfaceId:'ipad'}]; assert.equal(build({inventory:inv}).valid,false); });
test('unexpected caller authority fields fail closed',()=>{ assert.equal(build({inventory:inventory(),implementationAllowed:true}).valid,false); });
test('accessor-bearing top-level input fails closed without executing getter',()=>{ let calls=0; const packet={inventory:inventory()}; Object.defineProperty(packet,'extra',{enumerable:true,get(){calls+=1;throw new Error('no');}}); let out; assert.doesNotThrow(()=>{out=build(packet)}); assert.equal(out.valid,false); assert.equal(calls,0); });
test('custom-prototype inventory fails closed',()=>{ const inv=Object.create({valid:true}); Object.assign(inv,inventory()); assert.equal(build({inventory:inv}).valid,false); });
test('coverage nested accessors fail closed without executing caller code',()=>{ let calls=0; const inv=inventory(); Object.defineProperty(inv.coverage,'missingCanonical',{enumerable:true,configurable:true,get(){calls+=1;throw new Error('no');}}); let out; assert.doesNotThrow(()=>{out=build({inventory:inv})}); assert.equal(out.valid,false); assert.equal(calls,0); });
test('sparse and accessor-bearing covered canonical arrays fail closed',()=>{ const sparse=[]; sparse.length=ids.length; assert.equal(build({inventory:inventory({coverage:{canonicalTargetCount:ids.length,coveredCanonicalCount:ids.length,coveredCanonical:sparse,missingCanonical:[]}})}).valid,false); let calls=0; const covered=[...ids]; Object.defineProperty(covered,'0',{enumerable:true,configurable:true,get(){calls+=1;throw new Error('no');}}); let out; assert.doesNotThrow(()=>{out=build({inventory:inventory({coverage:{canonicalTargetCount:ids.length,coveredCanonicalCount:ids.length,coveredCanonical:covered,missingCanonical:[]}})})}); assert.equal(out.valid,false); assert.equal(calls,0); });
test('surface record accessors fail closed without execution',()=>{ let calls=0; const inv=inventory(); Object.defineProperty(inv.surfaces[0],'surfaceId',{enumerable:true,configurable:true,get(){calls+=1;throw new Error('no');}}); let out; assert.doesNotThrow(()=>{out=build({inventory:inv})}); assert.equal(out.valid,false); assert.equal(calls,0); });
test('revoked nested proxies fail closed without escaping',()=>{ const revocable=Proxy.revocable({canonicalTargetCount:ids.length,coveredCanonicalCount:ids.length,coveredCanonical:[...ids],missingCanonical:[]},{}); revocable.revoke(); const inv=inventory({coverage:revocable.proxy}); assert.doesNotThrow(()=>build({inventory:inv})); assert.equal(build({inventory:inv}).valid,false); });
test('coverage identities must match the canonical surface estate',()=>{ const inv=inventory(); inv.coverage.coveredCanonical=[...ids.slice(0,-1),'not-the-quest']; assert.equal(build({inventory:inv}).valid,false); });
test('caller mutation after build cannot rewrite the published contract',()=>{ const inv=inventory(); const out=build({inventory:inv}); inv.inventoryId='ui-inventory-mutated'; inv.surfaces[0].surfaceId='mutated'; inv.coverage.coveredCanonical.length=0; assert.equal(out.valid,true); assert.equal(out.inventoryId,'ui-inventory-test'); assert.equal(out.surfaces[0].surfaceId,'ai-console'); assert.equal(Object.isFrozen(out.surfaces),true); });
