import assert from 'node:assert/strict';
import test from 'node:test';
import { projectVrTeachingIntoSharedWorkspace, VR_RUNTIME_ACCEPTANCE_RECEIPT_SCHEMA_VERSION } from './vrTeachingWorkspaceProjectionV1.mjs';
const UPDATED_AT='2026-09-16T21:15:00.000Z';const SOURCE_REGISTRY=[{sourceId:'meta-xr-simulator',observedIdentity:'docs-2026-09-03'}];
function teaching(overrides={}){return{teachingKey:'teach:meta-xr-simulator:standalone-v1',candidateKey:'vrdisc:meta-xr-simulator:standalone-v1',sourceId:'meta-xr-simulator',observedIdentity:'docs-2026-09-03',evidencePlanes:['NORMATIVE_OR_OFFICIAL_SPECIFICATION','STEPHANOS_INFERENCE_OR_PROPOSAL'],confidence:'high-official-docs; derived-method-bounded',licenceBoundary:'Proprietary Meta tooling; method-level inference only.',reusableMethod:'Simulator-first OpenXR preflight followed by physical-headset proof.',proofRefs:['proofs/vr-teaching/meta-xr-simulator'],...overrides};}
function project(overrides={}){return projectVrTeachingIntoSharedWorkspace({sourceRegistry:SOURCE_REGISTRY,updatedAt:UPDATED_AT,nowMs:Date.parse(UPDATED_AT),...overrides});}
function runtimeReceipt(record,proofRef='proofs/runtime/accepted'){return{schemaVersion:VR_RUNTIME_ACCEPTANCE_RECEIPT_SCHEMA_VERSION,receiptId:'battle-bridge-runtime-acceptance-001',issuer:'battle-bridge-runtime-proof',verdict:'ACCEPTED',proofRef,sourceId:record.sourceId,observedIdentity:record.observedIdentity};}
test('projects governed teaching and emits content-bound receipt',()=>{const result=project({teachingRecords:[teaching()]});assert.equal(result.projectionReceipt.verdict,'VR_TEACHING_WORKSPACE_PROJECTION_READY');assert.equal(result.projectionReceipt.counters.projected,1);assert.match(result.projectionReceipt.contentDigest,/^sha256:[a-f0-9]{64}$/);});
test('deduplicates same stable teaching key and selects only an explicitly superseding revision',()=>{const old=teaching({observedIdentity:'docs-2026-09-03',freshnessIdentity:'2026-09-03',reusableMethod:'Old'}),fresh=teaching({observedIdentity:'docs-2026-09-17',freshnessIdentity:'2026-09-17',supersedesObservedIdentity:'docs-2026-09-03',reusableMethod:'Fresh'});const result=project({teachingRecords:[old,fresh],sourceRegistry:[{sourceId:'meta-xr-simulator',observedIdentity:'docs-2026-09-03'},{sourceId:'meta-xr-simulator',observedIdentity:'docs-2026-09-17'}]});assert.equal(result.projectionReceipt.verdict,'VR_TEACHING_WORKSPACE_PROJECTION_READY');assert.equal(result.projectionReceipt.counters.projected,1);assert.equal(result.projectionReceipt.counters.duplicatesSuppressed,1);assert.equal(result.projection.methodLibrary.find((entry)=>entry.teachingKey===fresh.teachingKey).reusableMethod,'Fresh');});
test('fails closed on differing revisions without explicit supersession',()=>{const v10=teaching({observedIdentity:'v10'}),v9=teaching({observedIdentity:'v9'}),sourceRegistry=[{sourceId:'meta-xr-simulator',observedIdentity:'v10'},{sourceId:'meta-xr-simulator',observedIdentity:'v9'}];for(const teachingRecords of [[v10,v9],[v9,v10]]){const result=project({teachingRecords,sourceRegistry});assert.equal(result.projectionReceipt.verdict,'VR_TEACHING_WORKSPACE_PROJECTION_BLOCKED');assert.equal(result.projectionReceipt.counters.projected,0);}});
test('blocks conflicting equal-identity revisions',()=>{const result=project({teachingRecords:[teaching({reusableMethod:'Method A'}),teaching({reusableMethod:'Method B'})]});assert.equal(result.projectionReceipt.verdict,'VR_TEACHING_WORKSPACE_PROJECTION_BLOCKED');});
test('blocks incomplete teaching',()=>{for(const patch of [{licenceBoundary:''},{confidence:'   '},{proofRefs:['   ']}])assert.equal(project({teachingRecords:[teaching(patch)]}).projectionReceipt.verdict,'VR_TEACHING_WORKSPACE_PROJECTION_BLOCKED');});
test('runtime evidence requires an exact authoritative Battle Bridge/operator receipt binding',()=>{const runtime=teaching({requiredProofLevel:'OBSERVED_RUNTIME_OR_HEADSET_PROOF',evidencePlanes:['OBSERVED_RUNTIME_OR_HEADSET_PROOF'],proofRefs:['proofs/runtime/accepted']}),receipt=runtimeReceipt(runtime);assert.equal(project({teachingRecords:[runtime]}).projectionReceipt.verdict,'VR_TEACHING_WORKSPACE_PROJECTION_BLOCKED');assert.equal(project({teachingRecords:[runtime],runtimeAcceptanceReceipts:[receipt]}).projectionReceipt.verdict,'VR_TEACHING_WORKSPACE_PROJECTION_BLOCKED');assert.equal(project({teachingRecords:[runtime],runtimeAcceptanceReceipts:[receipt],authoritativeRuntimeAcceptanceReceipts:[{...receipt,observedIdentity:'forged'}]}).projectionReceipt.verdict,'VR_TEACHING_WORKSPACE_PROJECTION_BLOCKED');assert.equal(project({teachingRecords:[runtime],runtimeAcceptanceReceipts:[receipt],authoritativeRuntimeAcceptanceReceipts:[receipt]}).projectionReceipt.verdict,'VR_TEACHING_WORKSPACE_PROJECTION_READY');});
test('requires canonical source registry and exact revision',()=>{assert.equal(project({teachingRecords:[teaching()]}).projectionReceipt.verdict,'VR_TEACHING_WORKSPACE_PROJECTION_READY');assert.equal(projectVrTeachingIntoSharedWorkspace({teachingRecords:[teaching()],updatedAt:UPDATED_AT}).projectionReceipt.verdict,'VR_TEACHING_WORKSPACE_PROJECTION_BLOCKED');assert.equal(project({teachingRecords:[teaching({observedIdentity:'wrong'})]}).projectionReceipt.verdict,'VR_TEACHING_WORKSPACE_PROJECTION_BLOCKED');});
test('binds component revisions to the named canonical component',()=>{const sourceRegistry={sources:[{source_id:'skyrim-vr-native-parity-ecosystem',higgs_snapshot_commit:'higgs-commit',vrik_version:'0.8.6'}]};const base=teaching({sourceId:'skyrim-vr-native-parity-ecosystem',observedIdentity:'higgs-commit'});assert.equal(project({sourceRegistry,teachingRecords:[base]}).projectionReceipt.verdict,'VR_TEACHING_WORKSPACE_PROJECTION_BLOCKED');assert.equal(project({sourceRegistry,teachingRecords:[{...base,sourceComponent:'vrik'}]}).projectionReceipt.verdict,'VR_TEACHING_WORKSPACE_PROJECTION_BLOCKED');const accepted=project({sourceRegistry,teachingRecords:[{...base,sourceComponent:'higgs'}]});assert.equal(accepted.projectionReceipt.verdict,'VR_TEACHING_WORKSPACE_PROJECTION_READY');assert.equal(accepted.projection.methodLibrary[0].sourceComponent,'higgs');});
test('preserves legacy existing knowledge',()=>{const result=project({teachingRecords:[],capabilityGraphCandidates:['cutscene-theatre',{candidateKey:'existing-graph'}],methodLibrary:[{teachingKey:'existing-method',reusableMethod:'Existing'}],proofRefs:['proofs/existing']});assert.equal(result.projection.capabilityGraphCandidates.length,2);assert.equal(result.projection.methodLibrary.length,1);});
test('receipt binding changes with authority-bearing teaching content',()=>{const left=project({teachingRecords:[teaching({reusableMethod:'Method A'})]}),right=project({teachingRecords:[teaching({reusableMethod:'Method B'})]});assert.notEqual(left.projectionReceipt.receiptId,right.projectionReceipt.receiptId);});
test('forbids self-confirmed projection',()=>{assert.equal(project({teachingRecords:[teaching({sharedWorkspaceProjectionState:'CONFIRMED'})]}).projectionReceipt.counters.policyBlocked,1);});
