import assert from 'node:assert/strict';import test from 'node:test';import { projectVrTeachingIntoSharedWorkspace } from './vrTeachingWorkspaceProjectionV1.mjs';
const UPDATED_AT='2026-09-16T21:15:00.000Z';function teaching(overrides={}){return{teachingKey:'teach:meta-xr-simulator:standalone-v1',candidateKey:'vrdisc:meta-xr-simulator:standalone-v1',sourceId:'meta-xr-simulator',observedIdentity:'docs-2026-09-03',evidencePlanes:['NORMATIVE_OR_OFFICIAL_SPECIFICATION','STEPHANOS_INFERENCE_OR_PROPOSAL'],confidence:'high-official-docs; derived-method-bounded',licenceBoundary:'Proprietary Meta tooling; method-level inference only.',reusableMethod:'Simulator-first OpenXR preflight followed by physical-headset proof.',proofRefs:['proofs/vr-teaching/meta-xr-simulator'],...overrides};}
test('projects governed teaching and emits content-bound receipt',()=>{const r=projectVrTeachingIntoSharedWorkspace({teachingRecords:[teaching()],updatedAt:UPDATED_AT,nowMs:Date.parse(UPDATED_AT)});assert.equal(r.projectionReceipt.verdict,'VR_TEACHING_WORKSPACE_PROJECTION_READY');assert.equal(r.projectionReceipt.counters.projected,1);assert.match(r.projectionReceipt.contentDigest,/^[a-f0-9]{64}$/);});
test('deduplicates same stable teaching key and deterministically selects superseding revision',()=>{const old=teaching({observedIdentity:'docs-2026-09-03',freshnessIdentity:'2026-09-03',reusableMethod:'Old'}),fresh=teaching({observedIdentity:'docs-2026-09-17',freshnessIdentity:'2026-09-17',reusableMethod:'Fresh'});const r=projectVrTeachingIntoSharedWorkspace({teachingRecords:[old,fresh],updatedAt:UPDATED_AT,nowMs:Date.parse(UPDATED_AT)});assert.equal(r.projectionReceipt.counters.projected,1);assert.equal(r.projectionReceipt.counters.duplicatesSuppressed,1);assert.equal(r.projection.methodLibrary.find((x)=>x.teachingKey===fresh.teachingKey).reusableMethod,'Fresh');});
test('blocks conflicting equal-identity revisions instead of hash-ranking authority-bearing content',()=>{const a=teaching({freshnessIdentity:'2026-09-17',observedIdentity:'docs-same',reusableMethod:'Method A'}),b=teaching({freshnessIdentity:'2026-09-17',observedIdentity:'docs-same',reusableMethod:'Method B'});const r=projectVrTeachingIntoSharedWorkspace({teachingRecords:[a,b],updatedAt:UPDATED_AT,nowMs:Date.parse(UPDATED_AT)});assert.equal(r.projectionReceipt.verdict,'VR_TEACHING_WORKSPACE_PROJECTION_BLOCKED');assert.equal(r.projectionReceipt.counters.projected,0);assert.equal(r.projectionReceipt.counters.policyBlocked,1);assert.deepEqual(r.projectionReceipt.policyBlocked[0].errors,['conflicting-equal-identity-revision']);});
test('blocks incomplete, unconfident and whitespace-proof teachings',()=>{for(const patch of [{licenceBoundary:''},{confidence:'   '},{proofRefs:['   ']}]){const r=projectVrTeachingIntoSharedWorkspace({teachingRecords:[teaching(patch)],updatedAt:UPDATED_AT,nowMs:Date.parse(UPDATED_AT)});assert.equal(r.projectionReceipt.verdict,'VR_TEACHING_WORKSPACE_PROJECTION_BLOCKED');assert.equal(r.projectionReceipt.counters.policyBlocked,1);}});
test('preserves legacy string graph candidates and existing knowledge',()=>{const r=projectVrTeachingIntoSharedWorkspace({teachingRecords:[],capabilityGraphCandidates:['cutscene-theatre',{candidateKey:'existing-graph'}],methodLibrary:[{teachingKey:'existing-method',reusableMethod:'Existing'}],proofRefs:['proofs/existing'],updatedAt:UPDATED_AT,nowMs:Date.parse(UPDATED_AT)});assert.deepEqual(r.projection.capabilityGraphCandidates,['cutscene-theatre',{candidateKey:'existing-graph'}]);assert.equal(r.projection.methodLibrary.length,1);assert.deepEqual(r.projection.proofRefs,['proofs/existing']);});
test('refresh replaces stale legacy candidate entry by candidate identity',()=>{const fresh=teaching({candidateKey:'legacy-candidate',observedIdentity:'docs-2026-09-17',reusableMethod:'Fresh method'});const r=projectVrTeachingIntoSharedWorkspace({teachingRecords:[fresh],capabilityGraphCandidates:[{candidateKey:'legacy-candidate',observedIdentity:'old'}],methodLibrary:[{teachingKey:fresh.teachingKey,reusableMethod:'Old'}],updatedAt:UPDATED_AT,nowMs:Date.parse(UPDATED_AT)});const candidates=r.projection.capabilityGraphCandidates.filter((x)=>x?.candidateKey==='legacy-candidate');assert.equal(candidates.length,1);assert.equal(candidates[0].observedIdentity,'docs-2026-09-17');assert.equal(r.projection.methodLibrary.find((x)=>x.teachingKey===fresh.teachingKey).reusableMethod,'Fresh method');});
test('receipt binding changes when authority-bearing teaching content changes',()=>{const a=projectVrTeachingIntoSharedWorkspace({teachingRecords:[teaching({reusableMethod:'Method A'})],updatedAt:UPDATED_AT,nowMs:Date.parse(UPDATED_AT)}),b=projectVrTeachingIntoSharedWorkspace({teachingRecords:[teaching({reusableMethod:'Method B'})],updatedAt:UPDATED_AT,nowMs:Date.parse(UPDATED_AT)});assert.notEqual(a.projectionReceipt.contentDigest,b.projectionReceipt.contentDigest);assert.notEqual(a.projectionReceipt.receiptId,b.projectionReceipt.receiptId);});
test('forbids self-confirmed projection',()=>{const r=projectVrTeachingIntoSharedWorkspace({teachingRecords:[teaching({sharedWorkspaceProjectionState:'CONFIRMED'})],updatedAt:UPDATED_AT,nowMs:Date.parse(UPDATED_AT)});assert.equal(r.projectionReceipt.counters.policyBlocked,1);});
