import { createHash } from 'node:crypto';

import { buildVrResearchWorkspaceProjection } from './vrResearchWorkspaceProjectionV1.mjs';
import { buildVrResearchAgentReadModel } from './vrResearchAgentV1.mjs';

export const VR_TEACHING_WORKSPACE_SCHEMA_VERSION = 'stephanos.vr-teaching-workspace-projection.v1';
export const VR_TEACHING_PROJECTION_VERDICT = Object.freeze({ READY: 'VR_TEACHING_WORKSPACE_PROJECTION_READY', BLOCKED: 'VR_TEACHING_WORKSPACE_PROJECTION_BLOCKED' });
const EVIDENCE_PLANES = new Set(['NORMATIVE_OR_OFFICIAL_SPECIFICATION','OFFICIAL_AUTHORING_EVIDENCE','DIRECT_PUBLIC_SOURCE_EVIDENCE','PUBLIC_PRODUCT_OR_CREATOR_CLAIM','APPROVED_LOCAL_PACKAGE_EVIDENCE','OBSERVED_RUNTIME_OR_HEADSET_PROOF','STEPHANOS_INFERENCE_OR_PROPOSAL']);
const RUNTIME_PROOF_LEVEL='OBSERVED_RUNTIME_OR_HEADSET_PROOF';
function text(value){return String(value??'').trim();}
function list(value){return Array.isArray(value)?value.filter((item)=>item!==null&&item!==undefined):[];}
function normalizedTextList(value){return [...new Set(list(value).map(text).filter(Boolean))].sort();}
function hash(value){return createHash('sha256').update(JSON.stringify(value)).digest('hex');}
function portableContentDigest(value){let digest=2166136261;for(let i=0;i<value.length;i++){digest^=value.charCodeAt(i);digest=Math.imul(digest,16777619)>>>0;}return `fnv1a32:${digest.toString(16).padStart(8,'0')}`;}
function stableIdentity(item){if(typeof item==='string')return `string:${text(item)}`;return text(item?.teachingKey)||text(item?.candidateKey)||text(item?.reusableMethod);}
function identityAliases(item){if(typeof item==='string')return new Set([`string:${text(item)}`]);return new Set([text(item?.teachingKey),text(item?.candidateKey)].filter(Boolean));}
function legacyMethodAlias(item){return item&&typeof item==='object'&&!text(item.teachingKey)&&!text(item.candidateKey)?text(item.reusableMethod):'';}
function aliasesOverlap(a,b){for(const key of a){if(b.has(key))return true;}return false;}
function graphEntriesOverlap(existing,fresh){const a=identityAliases(existing),b=identityAliases(fresh);if(a.size&&b.size)return aliasesOverlap(a,b);const legacy=legacyMethodAlias(existing);return Boolean(legacy&&legacy===text(fresh?.reusableMethod));}
function replaceByIdentity(existing,fresh,identity=stableIdentity){const freshKeys=new Set(fresh.map(identity).filter(Boolean));const combined=[...existing.filter((item)=>{const key=identity(item);return !key||!freshKeys.has(key);}),...fresh];const seen=new Set();return combined.filter((item)=>{const key=identity(item);if(!key)return true;if(seen.has(key))return false;seen.add(key);return true;});}
function replaceGraphByAliases(existing,fresh){const kept=existing.filter((item)=>!fresh.some((candidate)=>graphEntriesOverlap(item,candidate)));return [...kept,...fresh];}
function registryEntries(sourceRegistry){if(Array.isArray(sourceRegistry))return sourceRegistry;if(sourceRegistry&&typeof sourceRegistry==='object')return Object.entries(sourceRegistry).map(([sourceId,value])=>typeof value==='object'&&value?{sourceId,...value}:{sourceId,observedIdentity:value});return [];}
function validateRegisteredSource(sourceId,observedIdentity,sourceRegistry){if(sourceRegistry===undefined||sourceRegistry===null)return[];const entry=registryEntries(sourceRegistry).find((item)=>text(item.sourceId||item.id||item.canonicalSourceId)===sourceId);if(!entry)return['source-not-in-canonical-registry'];const registeredIdentity=text(entry.observedIdentity||entry.exactObservedIdentity||entry.revision||entry.freshnessIdentity);return registeredIdentity&&registeredIdentity!==observedIdentity?['source-revision-mismatch']:[];}
function runtimeAcceptanceRefs(input){return new Set(normalizedTextList(input.runtimeAcceptanceProofRefs||input.acceptedRuntimeProofRefs));}
function normalizeTeaching(record={},input={}){const teachingKey=text(record.teachingKey),candidateKey=text(record.candidateKey),sourceId=text(record.sourceId||record.canonicalSourceId),observedIdentity=text(record.observedIdentity||record.exactObservedIdentity);const evidencePlanes=normalizedTextList(record.evidencePlanes||[record.evidencePlane]);const proofRefs=normalizedTextList(record.proofRefs),confidence=text(record.confidence),requiredProofLevel=text(record.requiredProofLevel),errors=[];if(!teachingKey)errors.push('missing-teachingKey');if(!candidateKey)errors.push('missing-candidateKey');if(!sourceId)errors.push('missing-sourceId');if(!observedIdentity)errors.push('missing-observedIdentity');if(!confidence)errors.push('missing-confidence');if(!text(record.licenceBoundary||record.licenseBoundary))errors.push('missing-licence-boundary');if(!text(record.reusableMethod||record.capability))errors.push('missing-reusable-method');if(!proofRefs.length)errors.push('missing-proofRefs');if(!evidencePlanes.length||evidencePlanes.some((plane)=>!EVIDENCE_PLANES.has(plane)))errors.push('invalid-evidence-plane');errors.push(...validateRegisteredSource(sourceId,observedIdentity,input.sourceRegistry));if(requiredProofLevel===RUNTIME_PROOF_LEVEL){if(!evidencePlanes.includes(RUNTIME_PROOF_LEVEL))errors.push('required-runtime-proof-missing');const accepted=runtimeAcceptanceRefs(input);if(!proofRefs.some((ref)=>accepted.has(ref)))errors.push('runtime-acceptance-proof-missing');}if(text(record.sharedWorkspaceProjectionState).toUpperCase()==='CONFIRMED')errors.push('self-confirmed-projection-forbidden');return{valid:!errors.length,errors,value:Object.freeze({teachingKey,candidateKey,sourceId,observedIdentity,sourceCommentId:text(record.sourceCommentId),teachingCommentId:text(record.teachingCommentId),evidencePlanes:Object.freeze(evidencePlanes),confidence,licenceBoundary:text(record.licenceBoundary||record.licenseBoundary),reusableMethod:text(record.reusableMethod||record.capability),applicability:text(record.applicability),nonApplicability:text(record.nonApplicability),constraints:Object.freeze(normalizedTextList(record.constraints)),failureModes:Object.freeze(normalizedTextList(record.failureModes)),fallback:text(record.fallback),requiredProofLevel,freshnessIdentity:text(record.freshnessIdentity||observedIdentity),parityProjectionState:text(record.parityProjectionState||'NOT_APPLICABLE'),proofRefs:Object.freeze(proofRefs)})};}
function revisionIdentity(item){return `${text(item.freshnessIdentity)}\u0000${text(item.observedIdentity)}`;}
function selectRevisions(items){const selected=new Map(),duplicates=[],conflicts=[];for(const item of items){const key=item.teachingKey;const prior=selected.get(key);if(!prior){selected.set(key,item);continue;}duplicates.push(key);const itemRevision=revisionIdentity(item),priorRevision=revisionIdentity(prior);if(itemRevision===priorRevision){if(hash(item)!==hash(prior)){conflicts.push({teachingKey:key,errors:['conflicting-equal-identity-revision']});selected.delete(key);}continue;}if(itemRevision>priorRevision)selected.set(key,item);}return{accepted:[...selected.values()],duplicates,conflicts};}
function projectedTeachingContent(graph,methods,proofRefs){return{capabilityGraphCandidates:graph,methodLibrary:methods,proofRefs};}
function projectedTeachingDigest(graph,methods,proofRefs){return portableContentDigest(JSON.stringify(projectedTeachingContent(graph,methods,proofRefs)));}
export function projectVrTeachingIntoSharedWorkspace(input={}){const normalizedAccepted=[],blocked=[];for(const raw of list(input.teachingRecords)){const normalized=normalizeTeaching(raw,input);if(!normalized.valid){blocked.push({teachingKey:text(raw?.teachingKey),errors:normalized.errors});continue;}normalizedAccepted.push(normalized.value);}const {accepted,duplicates,conflicts}=selectRevisions(normalizedAccepted);blocked.push(...conflicts);const newGraphCandidates=accepted.map((item)=>Object.freeze({teachingKey:item.teachingKey,candidateKey:item.candidateKey,sourceId:item.sourceId,observedIdentity:item.observedIdentity,evidencePlanes:item.evidencePlanes,confidence:item.confidence,reusableMethod:item.reusableMethod,requiredProofLevel:item.requiredProofLevel,proofRefs:item.proofRefs}));const capabilityGraphCandidates=replaceGraphByAliases(list(input.capabilityGraphCandidates),newGraphCandidates);const methodLibrary=replaceByIdentity(list(input.methodLibrary),accepted.map((item)=>Object.freeze({...item})));const proofRefs=[...new Set([...normalizedTextList(input.proofRefs),...accepted.flatMap((item)=>item.proofRefs)])].sort();const projection=buildVrResearchWorkspaceProjection({...input,capabilityGraphCandidates,methodLibrary,proofRefs,updatedAt:text(input.updatedAt)||new Date().toISOString()});const agentReadModel=buildVrResearchAgentReadModel({workspaceProjection:projection,sourceRegistry:input.sourceRegistry,nowMs:input.nowMs});const contentBinding=JSON.stringify(projectedTeachingContent(capabilityGraphCandidates,methodLibrary,proofRefs));const contentDigest=projectedTeachingDigest(capabilityGraphCandidates,methodLibrary,proofRefs);const projectionReceipt=Object.freeze({schemaVersion:VR_TEACHING_WORKSPACE_SCHEMA_VERSION,receiptId:`vr-teaching-${hash({projectionId:projection.projectionId,contentDigest}).slice(0,20)}`,contentDigest,contentBinding,verdict:blocked.length?VR_TEACHING_PROJECTION_VERDICT.BLOCKED:VR_TEACHING_PROJECTION_VERDICT.READY,projectionId:projection.projectionId,teachingKeys:Object.freeze(accepted.map((item)=>item.teachingKey)),counters:Object.freeze({seen:list(input.teachingRecords).length,projected:accepted.length,duplicatesSuppressed:duplicates.length,policyBlocked:blocked.length}),duplicatesSuppressed:Object.freeze(duplicates),policyBlocked:Object.freeze(blocked),agentReadModelVerdict:agentReadModel.verdict,proofRefs:Object.freeze(proofRefs)});return Object.freeze({projection,agentReadModel,projectionReceipt});}
