import { createHash } from 'node:crypto';
import { buildVrResearchWorkspaceProjection } from './vrResearchWorkspaceProjectionV1.mjs';
import { buildVrResearchAgentReadModel } from './vrResearchAgentV1.mjs';
export const VR_TEACHING_WORKSPACE_SCHEMA_VERSION='stephanos.vr-teaching-workspace-projection.v1';
export const VR_RUNTIME_ACCEPTANCE_RECEIPT_SCHEMA_VERSION='stephanos.vr-runtime-acceptance-receipt.v1';
export const VR_TEACHING_PROJECTION_VERDICT=Object.freeze({READY:'VR_TEACHING_WORKSPACE_PROJECTION_READY',BLOCKED:'VR_TEACHING_WORKSPACE_PROJECTION_BLOCKED'});
const EVIDENCE_PLANES=new Set(['NORMATIVE_OR_OFFICIAL_SPECIFICATION','OFFICIAL_AUTHORING_EVIDENCE','DIRECT_PUBLIC_SOURCE_EVIDENCE','PUBLIC_PRODUCT_OR_CREATOR_CLAIM','APPROVED_LOCAL_PACKAGE_EVIDENCE','OBSERVED_RUNTIME_OR_HEADSET_PROOF','STEPHANOS_INFERENCE_OR_PROPOSAL']);
const RUNTIME_PROOF_LEVEL='OBSERVED_RUNTIME_OR_HEADSET_PROOF';
function text(v){return String(v??'').trim();} function list(v){return Array.isArray(v)?v.filter(x=>x!==null&&x!==undefined):[];}
function norm(v){return[...new Set(list(v).map(text).filter(Boolean))].sort();} function hash(v){return createHash('sha256').update(JSON.stringify(v)).digest('hex');}
function portable(v){let d=2166136261;for(let i=0;i<v.length;i++){d^=v.charCodeAt(i);d=Math.imul(d,16777619)>>>0;}return`fnv1a32:${d.toString(16).padStart(8,'0')}`;}
function aliases(i){if(typeof i==='string')return new Set([`string:${text(i)}`]);return new Set([text(i?.teachingKey),text(i?.candidateKey)].filter(Boolean));}
function legacyAlias(i){return i&&typeof i==='object'&&!text(i.teachingKey)&&!text(i.candidateKey)?text(i.reusableMethod):'';}
function overlap(a,b){const aa=aliases(a),bb=aliases(b);if(aa.size&&bb.size){for(const k of aa)if(bb.has(k))return true;return false;}const legacy=legacyAlias(a);return Boolean(legacy&&legacy===text(b?.reusableMethod));}
function replaceGraph(existing,fresh){return[...existing.filter(x=>!fresh.some(y=>overlap(x,y))),...fresh];}
function replaceMethods(existing,fresh){const keys=new Set(fresh.map(x=>text(x.teachingKey)||text(x.candidateKey)).filter(Boolean));return[...existing.filter(x=>!keys.has(text(x?.teachingKey)||text(x?.candidateKey))),...fresh];}
function registryEntries(r){if(Array.isArray(r))return r;if(r&&typeof r==='object'&&Array.isArray(r.sources))return r.sources;if(r&&typeof r==='object')return Object.entries(r).map(([sourceId,v])=>typeof v==='object'&&v?{sourceId,...v}:{sourceId,observedIdentity:v});return[];}
function registeredRevision(e){return text(e?.observedIdentity||e?.exactObservedIdentity||e?.revision||e?.freshnessIdentity||e?.snapshot_commit||e?.snapshot_version||e?.snapshot_release||e?.snapshot_date);}
function validateSource(sourceId,observedIdentity,r){if(r===undefined||r===null)return[];const e=registryEntries(r).find(x=>text(x.sourceId||x.source_id||x.id||x.canonicalSourceId||x.canonical_source_id)===sourceId);if(!e)return['source-not-in-canonical-registry'];const rev=registeredRevision(e);if(!rev)return['registered-source-revision-required'];return rev===observedIdentity?[]:['source-revision-mismatch'];}
function runtimeAccepted(input,record,refs){const typed=list(input.runtimeAcceptanceReceipts).some(r=>text(r?.schemaVersion)===VR_RUNTIME_ACCEPTANCE_RECEIPT_SCHEMA_VERSION&&text(r?.verdict)==='ACCEPTED'&&text(r?.proofRef)&&refs.includes(text(r.proofRef))&&text(r?.sourceId)===text(record.sourceId||record.canonicalSourceId)&&text(r?.observedIdentity)===text(record.observedIdentity||record.exactObservedIdentity));const legacy=new Set(norm(input.runtimeAcceptanceProofRefs||input.acceptedRuntimeProofRefs));return typed||refs.some(r=>legacy.has(r));}
function normalize(record={},input={}){const teachingKey=text(record.teachingKey),candidateKey=text(record.candidateKey),sourceId=text(record.sourceId||record.canonicalSourceId),observedIdentity=text(record.observedIdentity||record.exactObservedIdentity),evidencePlanes=norm(record.evidencePlanes||[record.evidencePlane]),proofRefs=norm(record.proofRefs),confidence=text(record.confidence),requiredProofLevel=text(record.requiredProofLevel),errors=[];if(!teachingKey)errors.push('missing-teachingKey');if(!candidateKey)errors.push('missing-candidateKey');if(!sourceId)errors.push('missing-sourceId');if(!observedIdentity)errors.push('missing-observedIdentity');if(!confidence)errors.push('missing-confidence');if(!text(record.licenceBoundary||record.licenseBoundary))errors.push('missing-licence-boundary');if(!text(record.reusableMethod||record.capability))errors.push('missing-reusable-method');if(!proofRefs.length)errors.push('missing-proofRefs');if(!evidencePlanes.length||evidencePlanes.some(p=>!EVIDENCE_PLANES.has(p)))errors.push('invalid-evidence-plane');errors.push(...validateSource(sourceId,observedIdentity,input.sourceRegistry));if(requiredProofLevel===RUNTIME_PROOF_LEVEL){if(!evidencePlanes.includes(RUNTIME_PROOF_LEVEL))errors.push('required-runtime-proof-missing');if(!runtimeAccepted(input,record,proofRefs))errors.push('runtime-acceptance-proof-missing');}if(text(record.sharedWorkspaceProjectionState).toUpperCase()==='CONFIRMED')errors.push('self-confirmed-projection-forbidden');return{valid:!errors.length,errors,value:Object.freeze({teachingKey,candidateKey,sourceId,observedIdentity,sourceCommentId:text(record.sourceCommentId),teachingCommentId:text(record.teachingCommentId),evidencePlanes:Object.freeze(evidencePlanes),confidence,licenceBoundary:text(record.licenceBoundary||record.licenseBoundary),reusableMethod:text(record.reusableMethod||record.capability),applicability:text(record.applicability),nonApplicability:text(record.nonApplicability),constraints:Object.freeze(norm(record.constraints)),failureModes:Object.freeze(norm(record.failureModes)),fallback:text(record.fallback),requiredProofLevel,freshnessIdentity:text(record.freshnessIdentity||observedIdentity),supersedesObservedIdentity:text(record.supersedesObservedIdentity),parityProjectionState:text(record.parityProjectionState||'NOT_APPLICABLE'),proofRefs:Object.freeze(proofRefs)})};}
function revision(i){return`${text(i.freshnessIdentity)}\u0000${text(i.observedIdentity)}`;} function explicit(a,b){return text(a.supersedesObservedIdentity)===text(b.observedIdentity);}
function select(items){const selected=new Map(),duplicates=[],conflicts=[];for(const item of items){const key=item.teachingKey,prior=selected.get(key);if(!prior){selected.set(key,item);continue;}duplicates.push(key);if(item.observedIdentity===prior.observedIdentity){if(hash(item)!==hash(prior)){conflicts.push({teachingKey:key,errors:['conflicting-equal-identity-revision']});selected.delete(key);}continue;}if(explicit(item,prior)||(!item.supersedesObservedIdentity&&!prior.supersedesObservedIdentity&&revision(item)>revision(prior))){selected.set(key,item);continue;}if(explicit(prior,item))continue;conflicts.push({teachingKey:key,errors:['unproven-revision-supersession']});selected.delete(key);}return{accepted:[...selected.values()],duplicates,conflicts};}
function content(graph,methods,proofRefs){return{capabilityGraphCandidates:graph,methodLibrary:methods,proofRefs};} function digest(g,m,p){return portable(JSON.stringify(content(g,m,p)));}
export function projectVrTeachingIntoSharedWorkspace(input={}){const normalized=[],blocked=[];for(const raw of list(input.teachingRecords)){const n=normalize(raw,input);if(!n.valid){blocked.push({teachingKey:text(raw?.teachingKey),errors:n.errors});continue;}normalized.push(n.value);}const{accepted,duplicates,conflicts}=select(normalized);blocked.push(...conflicts);const freshGraph=accepted.map(i=>Object.freeze({teachingKey:i.teachingKey,candidateKey:i.candidateKey,sourceId:i.sourceId,observedIdentity:i.observedIdentity,evidencePlanes:i.evidencePlanes,confidence:i.confidence,reusableMethod:i.reusableMethod,requiredProofLevel:i.requiredProofLevel,proofRefs:i.proofRefs}));const graph=replaceGraph(list(input.capabilityGraphCandidates),freshGraph),methods=replaceMethods(list(input.methodLibrary),accepted.map(i=>Object.freeze({...i}))),proofRefs=[...new Set([...norm(input.proofRefs),...accepted.flatMap(i=>i.proofRefs)])].sort();const projection=buildVrResearchWorkspaceProjection({...input,capabilityGraphCandidates:graph,methodLibrary:methods,proofRefs,updatedAt:text(input.updatedAt)||new Date().toISOString()});const agentReadModel=buildVrResearchAgentReadModel({workspaceProjection:projection,sourceRegistry:input.sourceRegistry,nowMs:input.nowMs});const contentBinding=JSON.stringify(content(projection.capabilityGraphCandidates,projection.methodLibrary,projection.proofRefs)),contentDigest=digest(projection.capabilityGraphCandidates,projection.methodLibrary,projection.proofRefs);const projectionReceipt=Object.freeze({schemaVersion:VR_TEACHING_WORKSPACE_SCHEMA_VERSION,receiptId:`vr-teaching-${hash({projectionId:projection.projectionId,contentDigest}).slice(0,20)}`,contentDigest,contentBinding,verdict:blocked.length?VR_TEACHING_PROJECTION_VERDICT.BLOCKED:VR_TEACHING_PROJECTION_VERDICT.READY,projectionId:projection.projectionId,teachingKeys:Object.freeze(accepted.map(i=>i.teachingKey)),counters:Object.freeze({seen:list(input.teachingRecords).length,projected:accepted.length,duplicatesSuppressed:duplicates.length,policyBlocked:blocked.length}),duplicatesSuppressed:Object.freeze(duplicates),policyBlocked:Object.freeze(blocked),agentReadModelVerdict:agentReadModel.verdict,proofRefs:Object.freeze(proofRefs)});return Object.freeze({projection,agentReadModel,projectionReceipt});}
