export const CAPABILITY_RADAR_CANDIDATES = [
  {
    id: 'mcp-official-servers', name: 'MCP Official Servers', source: 'modelcontextprotocol/servers', sourceUrl: 'https://github.com/modelcontextprotocol/servers',
    category: 'OpenClaw Control / Tool Bridge', why: 'Could provide supervised tool connection patterns for files, GitHub, browser, and services.', costPosture: 'zero-cost',
    localFirst: true, integrationDifficulty: 'medium', riskLevel: 'medium', relevance: 'high', activitySignal: 'active', licenseClarity: 'clear', docsQuality: 'good', securityPosture: 'review-needed', dependencyWeight: 'medium', strengthens: ['agent control', 'operator approval', 'canonical truth'], suggestedNextAction: 'REVIEW', tags: ['agent-related', 'openclaw-related']
  },
  { id: 'ollama-core', name: 'Ollama Core', source: 'ollama/ollama', sourceUrl: 'https://github.com/ollama/ollama', category: 'Local AI', why: 'Supports local-first AI routing and Battle Bridge model execution.', costPosture: 'zero-cost', localFirst: true, integrationDifficulty: 'medium', riskLevel: 'low-medium', relevance: 'critical', activitySignal: 'active', licenseClarity: 'clear', docsQuality: 'good', securityPosture: 'good', dependencyWeight: 'medium', strengthens: ['local ai', 'canonical truth'], suggestedNextAction: 'INTEGRATION_CANDIDATE', tags: ['agent-related'] },
  { id: 'llamaindex', name: 'LlamaIndex', source: 'run-llama/llama_index', sourceUrl: 'https://github.com/run-llama/llama_index', category: 'Memory / RAG', why: 'Useful patterns for local retrieval, document indexing, support snapshot search, and project memory.', costPosture: 'zero-cost', localFirst: true, integrationDifficulty: 'medium-high', riskLevel: 'medium', relevance: 'high', activitySignal: 'active', licenseClarity: 'clear', docsQuality: 'good', securityPosture: 'review-needed', dependencyWeight: 'high', strengthens: ['memory', 'telemetry'], suggestedNextAction: 'PROMPT_READY', tags: ['memory-rag'] },
  { id: 'langgraph', name: 'LangGraph', source: 'langchain-ai/langgraph', sourceUrl: 'https://github.com/langchain-ai/langgraph', category: 'Agent Layer', why: 'Useful patterns for stateful agent workflows, graph execution, checkpoints, and human-in-the-loop control.', costPosture: 'zero-cost', localFirst: true, integrationDifficulty: 'high', riskLevel: 'medium', relevance: 'medium-high', activitySignal: 'active', licenseClarity: 'clear', docsQuality: 'good', securityPosture: 'review-needed', dependencyWeight: 'high', strengthens: ['agent control', 'operator approval'], suggestedNextAction: 'WATCH', tags: ['agent-related'] },
  { id: 'n8n', name: 'n8n', source: 'n8n-io/n8n', sourceUrl: 'https://github.com/n8n-io/n8n', category: 'Workflow Automation', why: 'Powerful workflow automation, but must remain local-only/watch-only until security posture is reviewed.', costPosture: 'mixed', localFirst: true, integrationDifficulty: 'high', riskLevel: 'high', relevance: 'medium', activitySignal: 'active', licenseClarity: 'review-needed', docsQuality: 'good', securityPosture: 'risk-flagged', dependencyWeight: 'high', strengthens: ['workflow'], suggestedNextAction: 'BLOCKED_RISK', tags: ['risk-flagged'] },
  { id: 'hugging-face-spaces', name: 'Hugging Face Spaces', source: 'Hugging Face Spaces', sourceUrl: 'https://huggingface.co/spaces', category: 'Capability Discovery', why: 'Useful for discovering AI app patterns, demos, and multimodal tooling.', costPosture: 'zero-cost', localFirst: false, integrationDifficulty: 'low', riskLevel: 'medium', relevance: 'medium', activitySignal: 'active', licenseClarity: 'mixed', docsQuality: 'good', securityPosture: 'review-needed', dependencyWeight: 'low', strengthens: ['telemetry'], suggestedNextAction: 'REVIEW', tags: ['needs-review'] },
  { id: 'awesome-ai-agents', name: 'Awesome AI Agents 2026', source: 'caramaschiHG/awesome-ai-agents-2026', sourceUrl: 'https://github.com/caramaschiHG/awesome-ai-agents-2026', category: 'Discovery Index', why: 'Good radar input for broad ecosystem discovery; repos must still be verified directly.', costPosture: 'zero-cost', localFirst: true, integrationDifficulty: 'low', riskLevel: 'low-medium', relevance: 'medium', activitySignal: 'mixed', licenseClarity: 'mixed', docsQuality: 'mixed', securityPosture: 'review-needed', dependencyWeight: 'low', strengthens: ['operator approval'], suggestedNextAction: 'WATCH', tags: ['needs-review'] },
  { id: 'browser-automation-candidate', name: 'Open-source Browser Automation Candidate', source: 'mcpservers.org', sourceUrl: 'https://mcpservers.org', category: 'Browser Automation / OpenClaw Control', why: 'Could reduce repetitive click work but must be sandboxed and approval-gated.', costPosture: 'zero-cost', localFirst: true, integrationDifficulty: 'high', riskLevel: 'high', relevance: 'medium-high', activitySignal: 'mixed', licenseClarity: 'review-needed', docsQuality: 'mixed', securityPosture: 'risk-flagged', dependencyWeight: 'medium', strengthens: ['agent control', 'operator approval'], suggestedNextAction: 'SANDBOX_TEST', tags: ['openclaw-related', 'risk-flagged', 'agent-related'] },
];
