export const ERROR_CODES = {
  SIM_INPUT_INVALID: 'SIM_INPUT_INVALID',
  SIM_NOT_FOUND: 'SIM_NOT_FOUND',
  SIM_EXECUTION_FAILED: 'SIM_EXECUTION_FAILED',
  SIM_PRESET_NOT_FOUND: 'SIM_PRESET_NOT_FOUND',
  KG_INPUT_INVALID: 'KG_INPUT_INVALID',
  KG_NODE_NOT_FOUND: 'KG_NODE_NOT_FOUND',
  KG_EDGE_INVALID: 'KG_EDGE_INVALID',
  KG_DUPLICATE_NODE: 'KG_DUPLICATE_NODE',
  KG_STORAGE_FAILURE: 'KG_STORAGE_FAILURE',
  CMD_INVALID: 'CMD_INVALID',
  TOOL_EXECUTION_FAILED: 'TOOL_EXECUTION_FAILED',
  PROPOSAL_NOT_FOUND: 'PROPOSAL_NOT_FOUND',
  PROPOSAL_INVALID_STATE: 'PROPOSAL_INVALID_STATE',
  MEMORY_NOT_FOUND: 'MEMORY_NOT_FOUND',
  ACTIVITY_NOT_FOUND: 'ACTIVITY_NOT_FOUND',
  ROADMAP_NOT_FOUND: 'ROADMAP_NOT_FOUND',
  SIM_HISTORY_NOT_FOUND: 'SIM_HISTORY_NOT_FOUND',
  SIM_COMPARE_INVALID: 'SIM_COMPARE_INVALID',
  LLM_PROVIDER_INVALID: 'LLM_PROVIDER_INVALID',
  LLM_RESPONSE_UNSUPPORTED: 'LLM_RESPONSE_UNSUPPORTED',
  LLM_MOCK_SIMULATED_FAILURE: 'LLM_MOCK_SIMULATED_FAILURE',
  LLM_GROQ_MISSING_API_KEY: 'LLM_GROQ_MISSING_API_KEY',
  LLM_GROQ_REQUEST_FAILED: 'LLM_GROQ_REQUEST_FAILED',
  LLM_GEMINI_MISSING_API_KEY: 'LLM_GEMINI_MISSING_API_KEY',
  LLM_GEMINI_BAD_RESPONSE: 'LLM_GEMINI_BAD_RESPONSE',
  LLM_GEMINI_REQUEST_FAILED: 'LLM_GEMINI_REQUEST_FAILED',
  LLM_OLLAMA_UNREACHABLE: 'LLM_OLLAMA_UNREACHABLE',
  LLM_OLLAMA_MODEL_MISSING: 'LLM_OLLAMA_MODEL_MISSING',
  LLM_OPENROUTER_MISSING_API_KEY: 'LLM_OPENROUTER_MISSING_API_KEY',
  LLM_OPENROUTER_REQUEST_FAILED: 'LLM_OPENROUTER_REQUEST_FAILED',
  LLM_ROUTER_NO_PROVIDER_AVAILABLE: 'LLM_ROUTER_NO_PROVIDER_AVAILABLE',
};

export class AppError extends Error {
  constructor(code, message, { status = 400, details = null } = {}) {
    super(message);
    this.name = 'AppError';
    this.code = code;
    this.status = status;
    this.details = details;
  }
}

export function createError(code, message, options = {}) {
  return new AppError(code, message, options);
}

export function normalizeError(error) {
  if (error instanceof AppError) return error;
  return new AppError(ERROR_CODES.TOOL_EXECUTION_FAILED, error?.message ?? 'Unknown error.', { status: 500 });
}
