import { memoryService } from './memoryService.js';
import { listRegisteredAgents } from './agentRegistry.js';
import { knowledgeGraphService } from './knowledgeGraphService.js';
import { simulationEngine } from './simulationEngine.js';
import { listSimulations } from './simulationRegistry.js';
import { deletePreset, getPresetStatus, listPresets, loadPreset, savePreset } from './simulationPresets.js';
import { getSubsystemRegistry } from './subsystemRegistry.js';
import { createError, ERROR_CODES } from './errors.js';
import { proposalService } from './proposalService.js';
import { memoryProposalService } from './memoryProposalService.js';
import { activityLogService } from './activityLogService.js';
import { roadmapService } from './roadmapService.js';
import { simulationHistoryService } from './simulationHistoryService.js';
import { assistantContextService } from './assistantContextService.js';

const tools = [
  { name: 'getSystemStatus', description: 'Returns operational status for core Stephanos services.', category: 'system', subsystem: 'ai_core', state: 'live', async execute(_args, context) { return { output_text: 'Stephanos systems nominal.', data: { ai_available: context.aiAvailable, subsystems: getSubsystemRegistry(), app_version: process.env.APP_VERSION ?? '0.1.0' } }; } },
  { name: 'listSubsystems', description: 'Lists unified subsystem registry entries.', category: 'system', subsystem: 'ai_core', state: 'live', async execute() { return { output_text: 'Subsystem registry loaded.', data: { subsystems: getSubsystemRegistry() } }; } },
  { name: 'listAvailableTools', description: 'Lists all registered tools and their callability/state.', category: 'system', subsystem: 'tool_registry', state: 'live', async execute() { const grouped = tools.reduce((acc, tool) => { const key = `${tool.subsystem}:${tool.category}`; acc[key] = acc[key] ?? { subsystem: tool.subsystem, category: tool.category, tools: [] }; acc[key].tools.push({ name: tool.name, description: tool.description, state: tool.state, callable_now: tool.state === 'live' || tool.state === 'mock' }); return acc; }, {}); return { output_text: `Registered tools: ${tools.length}`, data: { tools: tools.map((t) => ({ name: t.name, description: t.description, category: t.category, subsystem: t.subsystem, state: t.state })), grouped_tools: Object.values(grouped) } }; } },
  { name: 'listAvailableAgents', description: 'Lists all registered agents and lifecycle state.', category: 'agents', subsystem: 'agent_registry', state: 'live', async execute() { const agents = listRegisteredAgents(); return { output_text: `Registered agents: ${agents.length}`, data: { agents } }; } },

  { name: 'listMemory', description: 'Lists persisted memory entries.', category: 'memory', subsystem: 'memory_service', state: 'live', async execute() { const items = memoryService.listMemory(); return { output_text: `Memory items: ${items.length}`, data: { items } }; } },
  { name: 'saveMemory', description: 'Persists a memory entry from user input text.', category: 'memory', subsystem: 'memory_service', state: 'live', async execute(args) { const text = (args?.text ?? '').trim(); if (!text) throw createError(ERROR_CODES.CMD_INVALID, 'Memory save requires text. Usage: /memory save <text>'); const saved = memoryService.saveMemory({ text }); return { output_text: `Saved memory ${saved.id}.`, data: { item: saved } }; } },
  { name: 'findMemory', description: 'Finds memory entries by substring match.', category: 'memory', subsystem: 'memory_service', state: 'live', async execute(args) { const query = (args?.query ?? '').trim(); if (!query) throw createError(ERROR_CODES.CMD_INVALID, 'Memory find requires query. Usage: /memory find <query>'); const matches = memoryService.findMemory(query); return { output_text: matches.length ? `Found ${matches.length} memory item(s).` : 'No memory matches found.', data: { query, matches } }; } },
  { name: 'memoryProposeById', description: 'Stages a graph proposal for one memory item.', category: 'memory', subsystem: 'proposal_queue', state: 'live', async execute(args) { const id = String(args?.id ?? '').trim(); if (!id) throw createError(ERROR_CODES.CMD_INVALID, 'Usage: /memory propose <memoryId>'); const proposal = memoryProposalService.proposeById(id); return { output_text: `Created proposal ${proposal.id} from memory ${id}.`, data: { proposal } }; } },
  { name: 'memoryProposeRecent', description: 'Stages a graph proposal from the most recent memory item.', category: 'memory', subsystem: 'proposal_queue', state: 'live', async execute() { const proposal = memoryProposalService.proposeRecent(); return { output_text: `Created proposal ${proposal.id} from recent memory.`, data: { proposal } }; } },

  { name: 'proposalList', description: 'List proposal queue entries.', category: 'proposals', subsystem: 'proposal_queue', state: 'live', async execute() { const proposals = proposalService.list(); return { output_text: `Proposals: ${proposals.length}`, data: { proposals } }; } },
  { name: 'proposalStats', description: 'Get proposal queue stats.', category: 'proposals', subsystem: 'proposal_queue', state: 'live', async execute() { const stats = proposalService.stats(); return { output_text: `Pending proposals: ${stats.pending}`, data: { stats } }; } },
  { name: 'proposalShow', description: 'Inspect one proposal.', category: 'proposals', subsystem: 'proposal_queue', state: 'live', async execute(args) { const proposal = proposalService.getById(args?.id); return { output_text: `Proposal ${proposal.id} loaded.`, data: { proposal } }; } },
  { name: 'proposalAccept', description: 'Accept and execute a pending proposal.', category: 'proposals', subsystem: 'proposal_queue', state: 'live', async execute(args) { const result = proposalService.accept(args?.id); return { output_text: `Accepted proposal ${args?.id}.`, data: result }; } },
  { name: 'proposalReject', description: 'Reject a pending proposal.', category: 'proposals', subsystem: 'proposal_queue', state: 'live', async execute(args) { const proposal = proposalService.reject(args?.id, args?.reason || 'rejected by user'); return { output_text: `Rejected proposal ${args?.id}.`, data: { proposal } }; } },

  { name: 'activityList', description: 'List full activity log.', category: 'activity', subsystem: 'activity_log', state: 'live', async execute() { const events = activityLogService.list(); return { output_text: `Activity events: ${events.length}`, data: { events } }; } },
  { name: 'activityRecent', description: 'List recent activity log events.', category: 'activity', subsystem: 'activity_log', state: 'live', async execute() { const events = activityLogService.recent(10); return { output_text: `Recent activity events: ${events.length}`, data: { events } }; } },
  { name: 'activityShow', description: 'Show one activity event.', category: 'activity', subsystem: 'activity_log', state: 'live', async execute(args) { const event = activityLogService.getById(args?.id); return { output_text: `Loaded activity event ${event.id}.`, data: { event } }; } },

  { name: 'roadmapList', description: 'List roadmap items.', category: 'roadmap', subsystem: 'roadmap_service', state: 'live', async execute() { const items = roadmapService.list(); return { output_text: `Roadmap items: ${items.length}`, data: { items, summary: roadmapService.getSummary() } }; } },
  { name: 'roadmapAdd', description: 'Add roadmap item.', category: 'roadmap', subsystem: 'roadmap_service', state: 'live', async execute(args) { const item = roadmapService.add(args?.text); return { output_text: `Roadmap item ${item.id} added.`, data: { item } }; } },
  { name: 'roadmapDone', description: 'Mark roadmap item done.', category: 'roadmap', subsystem: 'roadmap_service', state: 'live', async execute(args) { const item = roadmapService.markDone(args?.id); return { output_text: `Roadmap item ${item.id} marked done.`, data: { item } }; } },
  { name: 'roadmapShow', description: 'Show roadmap item.', category: 'roadmap', subsystem: 'roadmap_service', state: 'live', async execute(args) { const item = roadmapService.getById(args?.id); return { output_text: `Roadmap item ${item.id} loaded.`, data: { item } }; } },

  { name: 'kgGetStatus', description: 'Returns knowledge graph subsystem status.', category: 'knowledge_graph', subsystem: 'knowledge_graph_core', state: 'live', async execute() { return { output_text: 'Knowledge graph core is available.', data: { status: knowledgeGraphService.getStatus() } }; } },
  { name: 'kgListNodes', description: 'Lists all knowledge graph nodes.', category: 'knowledge_graph', subsystem: 'knowledge_graph_core', state: 'live', async execute() { const nodes = knowledgeGraphService.listNodes(); return { output_text: `Knowledge graph nodes: ${nodes.length}`, data: { nodes } }; } },
  { name: 'kgListEdges', description: 'Lists all knowledge graph edges.', category: 'knowledge_graph', subsystem: 'knowledge_graph_core', state: 'live', async execute() { const edges = knowledgeGraphService.listEdges(); return { output_text: `Knowledge graph edges: ${edges.length}`, data: { edges } }; } },
  { name: 'kgCreateNode', description: 'Creates a knowledge graph node.', category: 'knowledge_graph', subsystem: 'knowledge_graph_core', state: 'live', async execute(args) { const node = knowledgeGraphService.createNode(args); return { output_text: `Created node ${node.id}.`, data: { node } }; } },
  { name: 'kgUpdateNode', description: 'Updates a knowledge graph node.', category: 'knowledge_graph', subsystem: 'knowledge_graph_core', state: 'live', async execute(args) { const node = knowledgeGraphService.updateNode(args?.id, args); return { output_text: `Updated node ${node.id}.`, data: { node } }; } },
  { name: 'kgDeleteNode', description: 'Deletes a node and linked edges.', category: 'knowledge_graph', subsystem: 'knowledge_graph_core', state: 'live', async execute(args) { const outcome = knowledgeGraphService.deleteNode(args?.id); return { output_text: `Deleted node ${args?.id}.`, data: outcome }; } },
  { name: 'kgDeleteEdge', description: 'Deletes an edge by id.', category: 'knowledge_graph', subsystem: 'knowledge_graph_core', state: 'live', async execute(args) { const outcome = knowledgeGraphService.deleteEdge(args?.id); return { output_text: `Deleted edge ${args?.id}.`, data: outcome }; } },
  { name: 'kgCreateEdge', description: 'Creates a knowledge graph edge.', category: 'knowledge_graph', subsystem: 'knowledge_graph_core', state: 'live', async execute(args) { const edge = knowledgeGraphService.createEdge(args); return { output_text: `Created edge ${edge.id}.`, data: { edge } }; } },
  { name: 'kgSearch', description: 'Searches graph nodes and edges by text.', category: 'knowledge_graph', subsystem: 'knowledge_graph_core', state: 'live', async execute(args) { const query = (args?.query ?? '').trim(); const results = knowledgeGraphService.searchGraph(query); return { output_text: `Search found ${results.node_matches.length} node(s) and ${results.edge_matches.length} edge(s).`, data: results }; } },
  { name: 'kgFindRelated', description: 'Finds nodes related to a given node ID.', category: 'knowledge_graph', subsystem: 'knowledge_graph_core', state: 'live', async execute(args) { const nodeId = (args?.nodeId ?? '').trim(); if (!nodeId) throw createError(ERROR_CODES.CMD_INVALID, 'Usage: /kg related <nodeId>'); const result = knowledgeGraphService.findRelatedNodes(nodeId); return { output_text: `Found ${result.related.length} related node(s) for ${nodeId}.`, data: result }; } },
  { name: 'kgGetStats', description: 'Returns aggregate statistics for the knowledge graph.', category: 'knowledge_graph', subsystem: 'knowledge_graph_core', state: 'live', async execute() { const stats = knowledgeGraphService.getGraphStats(); return { output_text: `Graph stats: ${stats.totals.nodes} node(s), ${stats.totals.edges} edge(s).`, data: { stats } }; } },

  { name: 'simList', description: 'Lists all registered simulations.', category: 'simulation', subsystem: 'simulation_core', state: 'live', async execute() { const simulations = listSimulations(); return { output_text: `Registered simulations: ${simulations.length}`, data: { simulations } }; } },
  { name: 'simRun', description: 'Runs a simulation by ID with validated input.', category: 'simulation', subsystem: 'simulation_core', state: 'live', async execute(args = {}) { const simulationId = (args.simulationId ?? '').trim(); if (!simulationId) throw createError(ERROR_CODES.SIM_INPUT_INVALID, 'Simulation run requires simulationId. Usage: /simulate run <simulationId>'); const run = simulationEngine.runSimulation(simulationId, args.input ?? {}, { appVersion: process.env.APP_VERSION ?? '0.1.0', toolCount: tools.length }); const history = simulationHistoryService.recordRun({ simulationId, input: run.validatedInput, result: run.result, timingMs: run.timingMs, presetName: args.presetName ?? null }); return { output_text: `Simulation '${simulationId}' completed successfully.`, data: { simulationId, simulationName: run.simulation.name, category: run.simulation.category, input: run.validatedInput, result: run.result, execution_ms: run.timingMs, history_run: history } }; } },
  { name: 'simGetStatus', description: 'Returns simulation subsystem and preset status.', category: 'simulation', subsystem: 'simulation_core', state: 'live', async execute() { return { output_text: 'Simulation Core status available.', data: { engine: simulationEngine.getStatus(), presets: getPresetStatus(), history: simulationHistoryService.getStatus(), available_presets: listPresets().map((preset) => ({ name: preset.name, simulationId: preset.simulationId, updated_at: preset.updated_at })) } }; } },
  { name: 'simPresetList', description: 'List simulation presets.', category: 'simulation', subsystem: 'simulation_core', state: 'live', async execute() { const presets = listPresets(); return { output_text: `Presets: ${presets.length}`, data: { presets } }; } },
  { name: 'simPresetSave', description: 'Save simulation preset.', category: 'simulation', subsystem: 'simulation_core', state: 'live', async execute(args) { const preset = savePreset(args?.name, args?.simulationId, args?.input ?? {}); return { output_text: `Preset '${preset.name}' saved.`, data: { preset } }; } },
  { name: 'simPresetLoad', description: 'Load simulation preset.', category: 'simulation', subsystem: 'simulation_core', state: 'live', async execute(args) { const preset = loadPreset(args?.name); return { output_text: `Preset '${preset.name}' loaded.`, data: { preset } }; } },
  { name: 'simPresetDelete', description: 'Delete simulation preset.', category: 'simulation', subsystem: 'simulation_core', state: 'live', async execute(args) { const preset = deletePreset(args?.name); return { output_text: `Preset '${preset.name}' deleted.`, data: { preset } }; } },
  { name: 'simHistoryList', description: 'List simulation run history.', category: 'simulation', subsystem: 'simulation_history', state: 'live', async execute() { const runs = simulationHistoryService.list(); return { output_text: `Simulation history runs: ${runs.length}`, data: { runs } }; } },
  { name: 'simHistoryShow', description: 'Show one simulation history run.', category: 'simulation', subsystem: 'simulation_history', state: 'live', async execute(args) { const run = simulationHistoryService.getByRunId(args?.runId); return { output_text: `Loaded simulation run ${run.run_id}.`, data: { run } }; } },
  { name: 'simHistoryClear', description: 'Clear simulation history.', category: 'simulation', subsystem: 'simulation_history', state: 'live', async execute() { const result = simulationHistoryService.clear(); return { output_text: 'Simulation history cleared.', data: result }; } },
  { name: 'simCompareRuns', description: 'Compare two simulation runs.', category: 'simulation', subsystem: 'simulation_history', state: 'live', async execute(args) { if (!args?.runIdA || !args?.runIdB) throw createError(ERROR_CODES.SIM_COMPARE_INVALID, 'Usage: /simulate compare <runIdA> <runIdB>'); const comparison = simulationHistoryService.compare(args.runIdA, args.runIdB); return { output_text: comparison.summary, data: { comparison } }; } },

  { name: 'assistantContextBundle', description: 'Generate compact subsystem-aware assistant context.', category: 'assistant', subsystem: 'ai_core', state: 'live', async execute(args) { const context = assistantContextService.buildContextBundle(args ?? {}); return { output_text: 'Assistant context bundle generated.', data: { context } }; } },
];

export function getToolRegistry() { return [...tools]; }
export function getTool(name) { return tools.find((tool) => tool.name === name); }

export async function executeTool(name, args, context = {}) {
  const tool = getTool(name);
  if (!tool) throw createError(ERROR_CODES.CMD_INVALID, `Unknown tool '${name}'.`);
  if (tool.state === 'disabled' || tool.state === 'planned') throw createError(ERROR_CODES.CMD_INVALID, `Tool '${name}' is not callable in state '${tool.state}'.`);
  const result = await tool.execute(args, context);
  return { tool, result };
}
