import test from 'node:test';
import assert from 'node:assert/strict';
import {evaluateSourceMutationCommitGuard,SOURCE_MUTATION_LEASE_SCHEMA,SOURCE_MUTATION_REPOSITORY} from './source-mutation-commit-guard.mjs';
const NOW=Date.parse('2026-10-07T04:20:00.000Z'), HEAD='3af70a289d8c40470a4dc291d8a12f32fc7d0431';
function lease(overrides={}){return {schemaVersion:'shared-agent-workspace-record.v1',schema:SOURCE_MUTATION_LEASE_SCHEMA,status:'ACTIVE',leaseId:'lease-goal-2862-openclaw-local',laneId:'goal-2862-source-repair',repository:SOURCE_MUTATION_REPOSITORY,issueNumber:2862,prNumber:2862,branch:'repair/goal-2862',headSha:HEAD,ownerId:'openclaw-local',acquiredAtUtc:'2026-10-07T04:00:00.000Z',renewedAtUtc:'2026-10-07T04:15:00.000Z',expiresAtUtc:'2026-10-07T05:15:00.000Z',mergeAuthority:false,leaseSeizureAllowed:false,...overrides};}
test('local main is never a material builder commit surface',()=>{const r=evaluateSourceMutationCommitGuard({branch:'main',headSha:HEAD,lease:lease({branch:'main'}),nowMs:NOW,leaseHeadIsAncestor:true});assert.equal(r.ok,false);assert.equal(r.blocker,'SOURCE_MUTATION_ON_LOCAL_MAIN_FORBIDDEN');});
test('fresh branch-bound lease admits its descendant head',()=>{const r=evaluateSourceMutationCommitGuard({branch:'repair/goal-2862',headSha:HEAD,lease:lease(),nowMs:NOW,leaseHeadIsAncestor:true});assert.equal(r.ok,true);});
test('missing expired mismatched and unrelated leases fail closed',()=>{assert.equal(evaluateSourceMutationCommitGuard({branch:'repair/goal-2862',headSha:HEAD,lease:null,nowMs:NOW}).blocker,'SOURCE_MUTATION_LEASE_MISSING');assert.equal(evaluateSourceMutationCommitGuard({branch:'repair/goal-2862',headSha:HEAD,lease:lease({expiresAtUtc:'2026-10-07T04:19:59.000Z'}),nowMs:NOW,leaseHeadIsAncestor:true}).blocker,'SOURCE_MUTATION_LEASE_EXPIRED');assert.equal(evaluateSourceMutationCommitGuard({branch:'repair/other',headSha:HEAD,lease:lease(),nowMs:NOW,leaseHeadIsAncestor:true}).blocker,'SOURCE_MUTATION_LEASE_BRANCH_MISMATCH');assert.equal(evaluateSourceMutationCommitGuard({branch:'repair/goal-2862',headSha:HEAD,lease:lease(),nowMs:NOW,leaseHeadIsAncestor:false}).blocker,'SOURCE_MUTATION_LEASE_HEAD_NOT_ANCESTOR');});
test('lease cannot widen merge or seizure authority',()=>{assert.equal(evaluateSourceMutationCommitGuard({branch:'repair/goal-2862',headSha:HEAD,lease:lease({mergeAuthority:true}),nowMs:NOW,leaseHeadIsAncestor:true}).blocker,'SOURCE_MUTATION_LEASE_AUTHORITY_WIDENED');assert.equal(evaluateSourceMutationCommitGuard({branch:'repair/goal-2862',headSha:HEAD,lease:lease({leaseSeizureAllowed:true}),nowMs:NOW,leaseHeadIsAncestor:true}).blocker,'SOURCE_MUTATION_LEASE_AUTHORITY_WIDENED');});
