export const STEPHANOS_UI_VERSION = __STEPHANOS_UI_VERSION__;
export const STEPHANOS_UI_SOURCE = __STEPHANOS_UI_SOURCE__;
export const STEPHANOS_UI_BUILD_TARGET = __STEPHANOS_UI_BUILD_TARGET__;
export const STEPHANOS_UI_RUNTIME_LABEL = `Stephanos UI v${STEPHANOS_UI_VERSION} · target: ${STEPHANOS_UI_BUILD_TARGET} · source: ${STEPHANOS_UI_SOURCE}`;
export const STEPHANOS_UI_BOOT_LOG = `[Stephanos Runtime] ${STEPHANOS_UI_RUNTIME_LABEL}`;
